# Base interprofession Mangue

In [68]:
### importation des bibliothèque et importation de la base de donnée

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('Mangue.xlsx')
df.head()

,start,end,"Info : Cher(e) participant(e),Dans le cadre de cette enquête, des données personnelles seront collectées. Ces données serviront uniquement à l'actualisation de la base de données des familles membres de l'interprofession. Votre participation est volontaire et vous pouvez arrêter l’entretien à tout moment, sans aucune conséquence négative. Elles ne seront pas transmises à des tiers non impliqués dans l'activité.",Consentez-vous à la collecte et à l’utilisation de vos données comme décrit ci-dessus ?,Date de l’enquête :,Nom et prénoms de l’enquêteur :,Village de l'enquête :,Canton de l'enquête :,Région de l'enquête :,Type d'acteurs:,...,_uuid,_submission_time,_validation_status,_notes,_status,_submitted_by,__version__,_tags,meta/rootUuid,_index
0,2026-03-05 11:42:00.421,2026-03-06 04:44:32.597,NaN,"Oui, j’ai lu et compris la note d’information ...",2026-03-05,Doumougue daminsete,Namouk,Tamongue,Savane,Producteurs,...,b7dd5adb-cc24-489c-9889-cce88d0cae7a,2026-03-06 06:54:26,NaN,NaN,submitted_via_web,interpro2025,vqSJUew2F5SVkUF83MCFmW,NaN,uuid:b7dd5adb-cc24-489c-9889-cce88d0cae7a,1
1,2026-03-05 16:54:09.798,2026-03-06 05:02:08.086,NaN,"Oui, j’ai lu et compris la note d’information ...",2026-03-05,Doumougue daminsete,Namouk,Tamongue,Savanes,Producteurs,...,3b9ca15c-7dfc-46ab-9814-532e45e076b6,2026-03-06 06:54:27,NaN,NaN,submitted_via_web,interpro2025,vqSJUew2F5SVkUF83MCFmW,NaN,uuid:3b9ca15c-7dfc-46ab-9814-532e45e076b6,2
2,2026-03-09 11:36:33.665,2026-03-10 06:31:12.048,NaN,"Oui, j’ai lu et compris la note d’information ...",2026-03-09,Doumougue daminsete,Namouk,Tamongue,Savanes,Producteurs,...,c66f7bb6-76a9-42bd-9f6e-2988fd639367,2026-03-10 18:17:29,NaN,NaN,submitted_via_web,interpro2025,vqSJUew2F5SVkUF83MCFmW,NaN,uuid:c66f7bb6-76a9-42bd-9f6e-2988fd639367,3
3,2026-03-09 14:47:27.763,2026-03-10 06:38:04.365,NaN,"Oui, j’ai lu et compris la note d’information ...",2026-03-09,Doumougue damonsete,Namoik,Tamongue,Savanes,Producteurs,...,ce7bdbbc-8da7-4301-9f4a-7f02ad2578fb,2026-03-10 18:17:29,NaN,NaN,submitted_via_web,interpro2025,vqSJUew2F5SVkUF83MCFmW,NaN,uuid:ce7bdbbc-8da7-4301-9f4a-7f02ad2578fb,4
4,2026-03-16 13:09:25.646,2026-03-17 09:03:02.856,NaN,"Oui, j’ai lu et compris la note d’information ...",2026-03-16,Doumougue daminsete,Nayargue,Tamongue,Savanes,Producteurs,...,f08826ac-aebb-4fb6-998b-e1b7d7d7f3d0,2026-03-17 09:07:04,NaN,NaN,submitted_via_web,interpro2025,v8JwknAa6vyqwfyciyzXdf,NaN,uuid:f08826ac-aebb-4fb6-998b-e1b7d7d7f3d0,5

In [69]:
print(df.columns.tolist())

['start', 'end', "Info : Cher(e) participant(e),Dans le cadre de cette enquête, des données personnelles seront collectées. Ces données serviront uniquement à l'actualisation de la base de données des familles membres de l'interprofession. Votre participation est volontaire et vous pouvez arrêter l’entretien à tout moment, sans aucune conséquence négative. Elles ne seront pas transmises à des tiers non impliqués dans l'activité. ", 'Consentez-vous à la collecte et à l’utilisation de vos données comme décrit ci-dessus ?', 'Date de l’enquête : ', 'Nom et prénoms de l’enquêteur : ', "Village de l'enquête : ", "Canton de l'enquête : ", "Région de l'enquête : ", "Type d'acteurs: ", 'Nom et prénoms du répondant ', 'Sexe du répondant  : ', 'Niveau instruction du répondant : ', 'Numéro de téléphone principal: ', 'Numéro de téléphone secondaire : ', 'Adresse électronique (mail): ', 'Poste occupé par le répondant  : ', 'Nom et prénoms du premier responsable', 'Sexe du premier responsable : ', 'Adresse complète du premier responsable : ', 'Niveau instruction du premier responsable  : ', 'Numéro de téléphone principal du premier responsable :  ', 'Numéro de téléphone secondaire du premier responsable :  ', 'Adresse électronique (mail) du premier responsable : ', 'Statut sur le plan foncier du premier responsable : ', "Nom de l'organisation de base / structure ", 'Type d’organisation / structure', 'Autres ', 'Effectif des membres : ', 'Nombre de femmes : ', "Nombre d'hommes : ", "Date de création de l'organisation : ", "Numéro d'enregistrement / immatriculation : ", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : ', 'Adresse du siège de l’organisation : ', 'Coordonnées GPS du siège ou du premier responsable: ', '_Coordonnées GPS du siège ou du premier responsable: _latitude', '_Coordonnées GPS du siège ou du premier responsable: _longitude', '_Coordonnées GPS du siège ou du premier responsable: _altitude', '_Coordonnées GPS du siège ou du premier responsable: _precision', 'Adresse électronique de l’organisation à la base : ', 'Statut actuel de l’enquêté (organisation à la base) dans la famille : ', 'Nom de l’organisation communale / cantonale : ', 'Nom de l’organisation préfectorale :', "Nom de l'Union membre de la famille : ", 'Volume total moyen annuel de production de plants de mangue (pépinières) pour votre organisation : ', 'Variétés de mangue produites dans votre organisation : ', 'Variétés de mangue produites dans votre organisation : /Somnol', 'Variétés de mangue produites dans votre organisation : /Kents', 'Variétés de mangue produites dans votre organisation : /Eldonne', 'Variétés de mangue produites dans votre organisation : /Smith', 'Variétés de mangue produites dans votre organisation : /Mangue papaye ', 'Variétés de mangue produites dans votre organisation : /Gouverneur ', 'Variétés de mangue produites dans votre organisation : /Alfonse', 'Variétés de mangue produites dans votre organisation : /Cueillette', 'Variétés de mangue produites dans votre organisation : /Parlers ', 'Variétés de mangue produites dans votre organisation : /Camerounaise', 'Variétés de mangue produites dans votre organisation : /Rubis ', 'Variétés de mangue produites dans votre organisation : /Autres', 'Autres', 'Variété de mangue dominante dans votre organisation : ', 'Autres.1', 'Autres productions que vous effectuez à part les plants de mangue (pépinières) : ', 'Nom et prénoms du premier responsable.1', 'Sexe du premier responsable : .1', 'Adresse complète du premier responsable : .1', 'Niveau instruction du premier responsable  : .1', 'Numéro de téléphone principal du premier responsable :  .1', 'Numéro de téléphone secondaire du premier responsable :  .1', 'Adresse électronique (mail) du premier responsable : .1', 'Statut sur le plan foncier du premier responsable : .1', "Nom de l'organisation de base / structure .1", 'Type d’organisation / structure.1', 'Effectif des membres : .1', 'Nombre de femmes : .1', "Nombre d'hommes : .1", "Date de création de l'organisation : .1", "Numéro d'enregistrement / immatriculation : .1", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .1', 'Adresse du siège de l’organisation : .1', 'Coordonnées GPS du siège ou du premier responsable: .1', '_Coordonnées GPS du siège ou du premier responsable: _latitude.1', '_Coordonnées GPS du siège ou du premier responsable: _longitude.1', '_Coordonnées GPS du siège ou du premier responsable: _altitude.1', '_Coordonnées GPS du siège ou du premier responsable: _precision.1', 'Adresse électronique de l’organisation à la base : .1', 'Statut actuel de l’enquêté (organisation à la base) dans la famille : .1', 'Nom de l’organisation communale / cantonale : .1', 'Nom de l’organisation préfectorale :.1', "Nom de l'Union membre de la famille : .1", 'Superficie totale moyenne emblavée annuellement par votre organisation pour la production de mangue : ', 'Nombre total moyen de plants de manguiers de votre organisation pour la production de mangue  ', 'Variétés de mangue produites dans votre organisation : .1', 'Variétés de mangue produites dans votre organisation : /Somnol.1', 'Variétés de mangue produites dans votre organisation : /Kents.1', 'Variétés de mangue produites dans votre organisation : /Eldonne.1', 'Variétés de mangue produites dans votre organisation : /Smith.1', 'Variétés de mangue produites dans votre organisation : /Mangue papaye .1', 'Variétés de mangue produites dans votre organisation : /Gouverneur .1', 'Variétés de mangue produites dans votre organisation : /Alfonse.1', 'Variétés de mangue produites dans votre organisation : /Cueillette.1', 'Variétés de mangue produites dans votre organisation : /Parlers .1', 'Variétés de mangue produites dans votre organisation : /Camerounaise.1', 'Variétés de mangue produites dans votre organisation : /Rubis .1', 'Variétés de mangue produites dans votre organisation : /Autres.1', 'Autres.2', 'Variété de mangue dominante dans votre organisation : .1', 'Autres.3', 'Volume total moyen annuel de production de mangue de votre organisation : ', 'Autres productions que vous effectuez à part la mangue : ', 'Nom et prénoms du premier responsable.2', 'Sexe du premier responsable : .2', 'Adresse complète du premier responsable : .2', 'Niveau instruction du premier responsable  : .2', 'Numéro de téléphone principal du premier responsable :  .2', 'Numéro de téléphone secondaire du premier responsable :  .2', 'Adresse électronique (mail) du premier responsable : .2', 'Statut sur le plan foncier du premier responsable : .2', "Raison sociale de l'entreprise ", 'Statut juridique :', 'Autres: ', "Effectif des membres / personnels de l'entreprise : ", 'Nombre de femmes : .2', "Nombre d'hommes : .2", "Date de création de l'entreprise : ", "Numéro d'enregistrement / immatriculation : .2", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .2', 'Adresse du siège de l’entreprise: ', 'Coordonnées GPS : ', '_Coordonnées GPS : _latitude', '_Coordonnées GPS : _longitude', '_Coordonnées GPS : _altitude', '_Coordonnées GPS : _precision', 'Adresse électronique de l’entreprise : ', 'Statut actuel de l’enquêté (entreprise) dans la famille : ', "Statut sur le plan foncier (lieu d'installation de l'unité) ", 'Produits dérivés à base de mangue : ', 'Produits dérivés à base de mangue : /Jus de mangue ', 'Produits dérivés à base de mangue : /Mangue séchée', 'Produits dérivés à base de mangue : /Poudre ', 'Produits dérivés à base de mangue : /Sirop de mangue ', 'Produits dérivés à base de mangue : /Autres ', 'Produits dérivés à base de mangue : /Confiture de mangue', 'Autres.4', 'Produit dérivé spécifique à base de mangue dominant dans votre activité : ', 'Autres .1', 'Volume moyen annuel de produits achetés  :', 'Volume moyen annuel de produits vendus : ', 'Type de certification : ', "Nom de l'organisme certificateur : ", "Nom de l'organisme certificateur : /CCPB", "Nom de l'organisme certificateur : /ECOCERT", "Nom de l'organisme certificateur : /SRS", "Nom de l'organisme certificateur : /ONECERT", "Nom de l'organisme certificateur : /CONTROL UNION", "Nom de l'organisme certificateur : /UNION", "Nom de l'organisme certificateur : /CERES", "Nom de l'organisme certificateur : /Global Gap", "Nom de l'organisme certificateur : /Bio SPG", 'Autres produits que vous effectuez à part la mangue: ', 'Numéro de téléphone secondaire : .1', 'Numéro de téléphone principal du premier responsable :  .3', 'Numéro de téléphone secondaire du premier responsable :  .3', 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de mangue : ', 'Numéro de téléphone principal du premier responsable :  .4', 'Numéro de téléphone secondaire du premier responsable :  .4', 'Produits transformés à base de mangue :', "Volume total moyen annuel de mangue transformé par l'entreprise :", 'Volume moyen annuel de vente de mangue ou dérivés de la mangue de l’entreprise : ', 'Autres productions que vous effectuez à part la mangue: ', '_id', '_uuid', '_submission_time', '_validation_status', '_notes', '_status', '_submitted_by', '__version__', '_tags', 'meta/rootUuid', '_index']

In [70]:
df = df.drop( columns = ['start', 'end', "Info : Cher(e) participant(e),Dans le cadre de cette enquête, des données personnelles seront collectées. Ces données serviront uniquement à l'actualisation de la base de données des familles membres de l'interprofession. Votre participation est volontaire et vous pouvez arrêter l’entretien à tout moment, sans aucune conséquence négative. Elles ne seront pas transmises à des tiers non impliqués dans l'activité. ", 'Consentez-vous à la collecte et à l’utilisation de vos données comme décrit ci-dessus ?','_id', '_uuid', '_submission_time', '_validation_status', '_notes', '_status', '_submitted_by', '__version__', '_tags', 'meta/rootUuid',  "Nom de l'organisme certificateur : /CCPB", "Nom de l'organisme certificateur : /ECOCERT", "Nom de l'organisme certificateur : /SRS", "Nom de l'organisme certificateur : /ONECERT", "Nom de l'organisme certificateur : /CONTROL UNION", "Nom de l'organisme certificateur : /UNION", "Nom de l'organisme certificateur : /CERES", "Nom de l'organisme certificateur : /Global Gap", "Nom de l'organisme certificateur : /Bio SPG",'Variétés de mangue produites dans votre organisation : /Somnol', 'Variétés de mangue produites dans votre organisation : /Kents', 'Variétés de mangue produites dans votre organisation : /Eldonne', 'Variétés de mangue produites dans votre organisation : /Smith', 'Variétés de mangue produites dans votre organisation : /Mangue papaye ', 'Variétés de mangue produites dans votre organisation : /Gouverneur ', 'Variétés de mangue produites dans votre organisation : /Alfonse', 'Variétés de mangue produites dans votre organisation : /Cueillette', 'Variétés de mangue produites dans votre organisation : /Parlers ', 'Variétés de mangue produites dans votre organisation : /Camerounaise', 'Variétés de mangue produites dans votre organisation : /Rubis ', 'Variétés de mangue produites dans votre organisation : /Autres','Variétés de mangue produites dans votre organisation : /Somnol.1', 'Variétés de mangue produites dans votre organisation : /Kents.1', 'Variétés de mangue produites dans votre organisation : /Eldonne.1', 'Variétés de mangue produites dans votre organisation : /Smith.1', 'Variétés de mangue produites dans votre organisation : /Mangue papaye .1', 'Variétés de mangue produites dans votre organisation : /Gouverneur .1', 'Variétés de mangue produites dans votre organisation : /Alfonse.1', 'Variétés de mangue produites dans votre organisation : /Cueillette.1', 'Variétés de mangue produites dans votre organisation : /Parlers .1', 'Variétés de mangue produites dans votre organisation : /Camerounaise.1', 'Variétés de mangue produites dans votre organisation : /Rubis .1', 'Variétés de mangue produites dans votre organisation : /Autres.1','Produits dérivés à base de mangue : /Jus de mangue ', 'Produits dérivés à base de mangue : /Mangue séchée', 'Produits dérivés à base de mangue : /Poudre ', 'Produits dérivés à base de mangue : /Sirop de mangue ', 'Produits dérivés à base de mangue : /Autres ', 'Produits dérivés à base de mangue : /Confiture de mangue',"Nom de l'organisme certificateur : /CCPB", "Nom de l'organisme certificateur : /ECOCERT", "Nom de l'organisme certificateur : /SRS", "Nom de l'organisme certificateur : /ONECERT", "Nom de l'organisme certificateur : /CONTROL UNION", "Nom de l'organisme certificateur : /UNION", "Nom de l'organisme certificateur : /CERES", "Nom de l'organisme certificateur : /Global Gap", "Nom de l'organisme certificateur : /Bio SPG",'_index'])

In [71]:
print(df.columns.tolist())

['Date de l’enquête : ', 'Nom et prénoms de l’enquêteur : ', "Village de l'enquête : ", "Canton de l'enquête : ", "Région de l'enquête : ", "Type d'acteurs: ", 'Nom et prénoms du répondant ', 'Sexe du répondant  : ', 'Niveau instruction du répondant : ', 'Numéro de téléphone principal: ', 'Numéro de téléphone secondaire : ', 'Adresse électronique (mail): ', 'Poste occupé par le répondant  : ', 'Nom et prénoms du premier responsable', 'Sexe du premier responsable : ', 'Adresse complète du premier responsable : ', 'Niveau instruction du premier responsable  : ', 'Numéro de téléphone principal du premier responsable :  ', 'Numéro de téléphone secondaire du premier responsable :  ', 'Adresse électronique (mail) du premier responsable : ', 'Statut sur le plan foncier du premier responsable : ', "Nom de l'organisation de base / structure ", 'Type d’organisation / structure', 'Autres ', 'Effectif des membres : ', 'Nombre de femmes : ', "Nombre d'hommes : ", "Date de création de l'organisation : ", "Numéro d'enregistrement / immatriculation : ", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : ', 'Adresse du siège de l’organisation : ', 'Coordonnées GPS du siège ou du premier responsable: ', '_Coordonnées GPS du siège ou du premier responsable: _latitude', '_Coordonnées GPS du siège ou du premier responsable: _longitude', '_Coordonnées GPS du siège ou du premier responsable: _altitude', '_Coordonnées GPS du siège ou du premier responsable: _precision', 'Adresse électronique de l’organisation à la base : ', 'Statut actuel de l’enquêté (organisation à la base) dans la famille : ', 'Nom de l’organisation communale / cantonale : ', 'Nom de l’organisation préfectorale :', "Nom de l'Union membre de la famille : ", 'Volume total moyen annuel de production de plants de mangue (pépinières) pour votre organisation : ', 'Variétés de mangue produites dans votre organisation : ', 'Autres', 'Variété de mangue dominante dans votre organisation : ', 'Autres.1', 'Autres productions que vous effectuez à part les plants de mangue (pépinières) : ', 'Nom et prénoms du premier responsable.1', 'Sexe du premier responsable : .1', 'Adresse complète du premier responsable : .1', 'Niveau instruction du premier responsable  : .1', 'Numéro de téléphone principal du premier responsable :  .1', 'Numéro de téléphone secondaire du premier responsable :  .1', 'Adresse électronique (mail) du premier responsable : .1', 'Statut sur le plan foncier du premier responsable : .1', "Nom de l'organisation de base / structure .1", 'Type d’organisation / structure.1', 'Effectif des membres : .1', 'Nombre de femmes : .1', "Nombre d'hommes : .1", "Date de création de l'organisation : .1", "Numéro d'enregistrement / immatriculation : .1", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .1', 'Adresse du siège de l’organisation : .1', 'Coordonnées GPS du siège ou du premier responsable: .1', '_Coordonnées GPS du siège ou du premier responsable: _latitude.1', '_Coordonnées GPS du siège ou du premier responsable: _longitude.1', '_Coordonnées GPS du siège ou du premier responsable: _altitude.1', '_Coordonnées GPS du siège ou du premier responsable: _precision.1', 'Adresse électronique de l’organisation à la base : .1', 'Statut actuel de l’enquêté (organisation à la base) dans la famille : .1', 'Nom de l’organisation communale / cantonale : .1', 'Nom de l’organisation préfectorale :.1', "Nom de l'Union membre de la famille : .1", 'Superficie totale moyenne emblavée annuellement par votre organisation pour la production de mangue : ', 'Nombre total moyen de plants de manguiers de votre organisation pour la production de mangue  ', 'Variétés de mangue produites dans votre organisation : .1', 'Autres.2', 'Variété de mangue dominante dans votre organisation : .1', 'Autres.3', 'Volume total moyen annuel de production de mangue de votre organisation : ', 'Autres productions que vous effectuez à part la mangue : ', 'Nom et prénoms du premier responsable.2', 'Sexe du premier responsable : .2', 'Adresse complète du premier responsable : .2', 'Niveau instruction du premier responsable  : .2', 'Numéro de téléphone principal du premier responsable :  .2', 'Numéro de téléphone secondaire du premier responsable :  .2', 'Adresse électronique (mail) du premier responsable : .2', 'Statut sur le plan foncier du premier responsable : .2', "Raison sociale de l'entreprise ", 'Statut juridique :', 'Autres: ', "Effectif des membres / personnels de l'entreprise : ", 'Nombre de femmes : .2', "Nombre d'hommes : .2", "Date de création de l'entreprise : ", "Numéro d'enregistrement / immatriculation : .2", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .2', 'Adresse du siège de l’entreprise: ', 'Coordonnées GPS : ', '_Coordonnées GPS : _latitude', '_Coordonnées GPS : _longitude', '_Coordonnées GPS : _altitude', '_Coordonnées GPS : _precision', 'Adresse électronique de l’entreprise : ', 'Statut actuel de l’enquêté (entreprise) dans la famille : ', "Statut sur le plan foncier (lieu d'installation de l'unité) ", 'Produits dérivés à base de mangue : ', 'Autres.4', 'Produit dérivé spécifique à base de mangue dominant dans votre activité : ', 'Autres .1', 'Volume moyen annuel de produits achetés  :', 'Volume moyen annuel de produits vendus : ', 'Type de certification : ', "Nom de l'organisme certificateur : ", 'Autres produits que vous effectuez à part la mangue: ', 'Numéro de téléphone secondaire : .1', 'Numéro de téléphone principal du premier responsable :  .3', 'Numéro de téléphone secondaire du premier responsable :  .3', 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de mangue : ', 'Numéro de téléphone principal du premier responsable :  .4', 'Numéro de téléphone secondaire du premier responsable :  .4', 'Produits transformés à base de mangue :', "Volume total moyen annuel de mangue transformé par l'entreprise :", 'Volume moyen annuel de vente de mangue ou dérivés de la mangue de l’entreprise : ', 'Autres productions que vous effectuez à part la mangue: ']

In [72]:
renommer_colonnes = {
    # --- IDENTIFICATION DE L'ENQUÊTE ET DU RÉPONDANT ---
    'Date de l’enquête : ': 'date_enquete',
    'Nom et prénoms de l’enquêteur : ': 'nom_enqueteur',
    "Village de l'enquête : ": 'village',
    "Canton de l'enquête : ": 'canton',
    "Région de l'enquête : ": 'region',
    "Type d'acteurs: ": 'type_acteur',
    'Nom et prénoms du répondant ': 'nom_repondant',
    'Sexe du répondant  : ': 'sexe_repondant',
    'Niveau instruction du répondant : ': 'niveau_instruction_repondant',
    'Numéro de téléphone principal: ': 'tel_principal_repondant',
    'Numéro de téléphone secondaire : ': 'tel_secondaire_repondant',
    'Adresse électronique (mail): ': 'email_repondant',
    'Poste occupé par le répondant  : ': 'poste_repondant',

    # --- PROFIL 1 (ex: Pépiniéristes) ---
    'Nom et prénoms du premier responsable': 'nom_resp',
    'Sexe du premier responsable : ': 'sexe_resp',
    'Adresse complète du premier responsable : ': 'adresse_resp',
    'Niveau instruction du premier responsable  : ': 'niveau_instruction_resp',
    'Numéro de téléphone principal du premier responsable :  ': 'tel_principal_resp',
    'Numéro de téléphone secondaire du premier responsable :  ': 'tel_secondaire_resp',
    'Adresse électronique (mail) du premier responsable : ': 'email_resp',
    'Statut sur le plan foncier du premier responsable : ': 'statut_foncier_resp',
    "Nom de l'organisation de base / structure ": 'nom_org',
    'Type d’organisation / structure': 'type_org',
    'Autres ': 'type_org_autres',
    'Effectif des membres : ': 'effectif_membres',
    'Nombre de femmes : ': 'nb_femmes',
    "Nombre d'hommes : ": 'nb_hommes',
    "Date de création de l'organisation : ": 'date_creation_org',
    "Numéro d'enregistrement / immatriculation : ": 'num_immatriculation',
    'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : ': 'date_immatriculation_org',
    'Adresse du siège de l’organisation : ': 'adresse_siege_org',
    'Coordonnées GPS du siège ou du premier responsable: ': 'gps_org',
    '_Coordonnées GPS du siège ou du premier responsable: _latitude': 'gps_org_lat',
    '_Coordonnées GPS du siège ou du premier responsable: _longitude': 'gps_org_lon',
    '_Coordonnées GPS du siège ou du premier responsable: _altitude': 'gps_org_alt',
    '_Coordonnées GPS du siège ou du premier responsable: _precision': 'gps_org_prec',
    'Adresse électronique de l’organisation à la base : ': 'email_org',
    'Statut actuel de l’enquêté (organisation à la base) dans la famille : ': 'statut_famille_org',
    'Nom de l’organisation communale / cantonale : ': 'nom_org_communale',
    'Nom de l’organisation préfectorale :': 'nom_org_prefectorale',
    "Nom de l'Union membre de la famille : ": 'nom_union_famille',
    'Volume total moyen annuel de production de plants de mangue (pépinières) pour votre organisation : ': 'vol_prod_plants',
    'Variétés de mangue produites dans votre organisation : ': 'varietes_mangue',
    'Autres': 'varietes_mangue_autres',
    'Variété de mangue dominante dans votre organisation : ': 'variete_mangue_dom',
    'Autres.1': 'variete_mangue_dom_autres',
    'Autres productions que vous effectuez à part les plants de mangue (pépinières) : ': 'autres_prods_pepiniere',

    # --- PROFIL 2 (.1) (ex: Producteurs) ---
    'Nom et prénoms du premier responsable.1': 'nom_resp_prod',
    'Sexe du premier responsable : .1': 'sexe_resp_prod',
    'Adresse complète du premier responsable : .1': 'adresse_resp_prod',
    'Niveau instruction du premier responsable  : .1': 'niveau_instruction_resp_prod',
    'Numéro de téléphone principal du premier responsable :  .1': 'tel_principal_resp_prod',
    'Numéro de téléphone secondaire du premier responsable :  .1': 'tel_secondaire_resp_prod',
    'Adresse électronique (mail) du premier responsable : .1': 'email_resp_prod',
    'Statut sur le plan foncier du premier responsable : .1': 'statut_foncier_resp_prod',
    "Nom de l'organisation de base / structure .1": 'nom_org_prod',
    'Type d’organisation / structure.1': 'type_org_prod',
    'Effectif des membres : .1': 'effectif_membres_prod',
    'Nombre de femmes : .1': 'nb_femmes_prod',
    "Nombre d'hommes : .1": 'nb_hommes_prod',
    "Date de création de l'organisation : .1": 'date_creation_org_prod',
    "Numéro d'enregistrement / immatriculation : .1": 'num_immatriculation_prod',
    'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .1': 'date_immatriculation_org_prod',
    'Adresse du siège de l’organisation : .1': 'adresse_siege_org_prod',
    'Coordonnées GPS du siège ou du premier responsable: .1': 'gps_org_prod',
    '_Coordonnées GPS du siège ou du premier responsable: _latitude.1': 'gps_org_prod_lat',
    '_Coordonnées GPS du siège ou du premier responsable: _longitude.1': 'gps_org_prod_lon',
    '_Coordonnées GPS du siège ou du premier responsable: _altitude.1': 'gps_org_prod_alt',
    '_Coordonnées GPS du siège ou du premier responsable: _precision.1': 'gps_org_prod_prec',
    'Adresse électronique de l’organisation à la base : .1': 'email_org_prod',
    'Statut actuel de l’enquêté (organisation à la base) dans la famille : .1': 'statut_famille_org_prod',
    'Nom de l’organisation communale / cantonale : .1': 'nom_org_communale_prod',
    'Nom de l’organisation préfectorale :.1': 'nom_org_prefectorale_prod',
    "Nom de l'Union membre de la famille : .1": 'nom_union_famille_prod',
    'Superficie totale moyenne emblavée annuellement par votre organisation pour la production de mangue : ': 'superficie_mangue_org',
    'Nombre total moyen de plants de manguiers de votre organisation pour la production de mangue  ': 'nb_plants_manguiers',
    'Variétés de mangue produites dans votre organisation : .1': 'varietes_mangue_prod',
    'Autres.2': 'varietes_mangue_prod_autres',
    'Variété de mangue dominante dans votre organisation : .1': 'variete_mangue_dom_prod',
    'Autres.3': 'variete_mangue_dom_prod_autres',
    'Volume total moyen annuel de production de mangue de votre organisation : ': 'vol_prod_mangue',
    'Autres productions que vous effectuez à part la mangue : ': 'autres_prods_mangue',
    'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de mangue : ': 'superficie_mangue_membres',

    # --- PROFIL 3 (.2, .3, .4) (ex: Entreprises / Transformateurs) ---
    'Nom et prénoms du premier responsable.2': 'nom_resp_ent',
    'Sexe du premier responsable : .2': 'sexe_resp_ent',
    'Adresse complète du premier responsable : .2': 'adresse_resp_ent',
    'Niveau instruction du premier responsable  : .2': 'niveau_instruction_resp_ent',
    'Numéro de téléphone principal du premier responsable :  .2': 'tel_principal_resp_ent',
    'Numéro de téléphone secondaire du premier responsable :  .2': 'tel_secondaire_resp_ent',
    'Adresse électronique (mail) du premier responsable : .2': 'email_resp_ent',
    'Statut sur le plan foncier du premier responsable : .2': 'statut_foncier_resp_ent',
    "Raison sociale de l'entreprise ": 'nom_ent',
    'Statut juridique :': 'statut_juridique_ent',
    'Autres: ': 'statut_juridique_ent_autres',
    "Effectif des membres / personnels de l'entreprise : ": 'effectif_personnel_ent',
    'Nombre de femmes : .2': 'nb_femmes_ent',
    "Nombre d'hommes : .2": 'nb_hommes_ent',
    "Date de création de l'entreprise : ": 'date_creation_ent',
    "Numéro d'enregistrement / immatriculation : .2": 'num_immatriculation_ent',
    'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .2': 'date_immatriculation_ent',
    'Adresse du siège de l’entreprise: ': 'adresse_siege_ent',
    'Coordonnées GPS : ': 'gps_ent',
    '_Coordonnées GPS : _latitude': 'gps_ent_lat',
    '_Coordonnées GPS : _longitude': 'gps_ent_lon',
    '_Coordonnées GPS : _altitude': 'gps_ent_alt',
    '_Coordonnées GPS : _precision': 'gps_ent_prec',
    'Adresse électronique de l’entreprise : ': 'email_ent',
    'Statut actuel de l’enquêté (entreprise) dans la famille : ': 'statut_famille_ent',
    "Statut sur le plan foncier (lieu d'installation de l'unité) ": 'statut_foncier_unite',
    'Produits dérivés à base de mangue : ': 'produits_derives',
    'Autres.4': 'produits_derives_autres',
    'Produit dérivé spécifique à base de mangue dominant dans votre activité : ': 'produit_derive_dom',
    'Autres .1': 'produit_derive_dom_autres',
    'Volume moyen annuel de produits achetés  :': 'vol_achats',
    'Volume moyen annuel de produits vendus : ': 'vol_ventes',
    'Type de certification : ': 'type_certif',
    "Nom de l'organisme certificateur : ": 'organisme_certif',
    'Autres produits que vous effectuez à part la mangue: ': 'autres_produits_ent',
    'Produits transformés à base de mangue :': 'produits_transformes',
    "Volume total moyen annuel de mangue transformé par l'entreprise :": 'vol_transforme',
    'Volume moyen annuel de vente de mangue ou dérivés de la mangue de l’entreprise : ': 'vol_ventes_derives',
    'Autres productions que vous effectuez à part la mangue: ': 'autres_prods_ent',

    # --- VARIABLES RÉSIDUELLES (Doublons de téléphone) ---
    'Numéro de téléphone secondaire : .1': 'tel_secondaire_repondant_alt',
    'Numéro de téléphone principal du premier responsable :  .3': 'tel_principal_resp_alt_3',
    'Numéro de téléphone secondaire du premier responsable :  .3': 'tel_secondaire_resp_alt_3',
    'Numéro de téléphone principal du premier responsable :  .4': 'tel_principal_resp_alt_4',
    'Numéro de téléphone secondaire du premier responsable :  .4': 'tel_secondaire_resp_alt_4'
}
   
df = df.rename( columns = renommer_colonnes)
df.head()

,date_enquete,nom_enqueteur,village,canton,region,type_acteur,nom_repondant,sexe_repondant,niveau_instruction_repondant,tel_principal_repondant,...,tel_secondaire_repondant_alt,tel_principal_resp_alt_3,tel_secondaire_resp_alt_3,superficie_mangue_membres,tel_principal_resp_alt_4,tel_secondaire_resp_alt_4,produits_transformes,vol_transforme,vol_ventes_derives,autres_prods_ent
0,2026-03-05,Doumougue daminsete,Namouk,Tamongue,Savane,Producteurs,Lare gani,Homme,Aucun,93145658,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-05,Doumougue daminsete,Namouk,Tamongue,Savanes,Producteurs,Kombate limanguedame,Homme,Aucun,71490229,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-03-09,Doumougue daminsete,Namouk,Tamongue,Savanes,Producteurs,Lare noaka,Homme,Aucun,93149192,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-03-09,Doumougue damonsete,Namoik,Tamongue,Savanes,Producteurs,Doumougue daminsete,Homme,Primaire,97340009,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-03-16,Doumougue daminsete,Nayargue,Tamongue,Savanes,Producteurs,Kolani poukinin,Homme,Aucun,90606437,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
print(df.columns.tolist())

['date_enquete', 'nom_enqueteur', 'village', 'canton', 'region', 'type_acteur', 'nom_repondant', 'sexe_repondant', 'niveau_instruction_repondant', 'tel_principal_repondant', 'tel_secondaire_repondant', 'email_repondant', 'poste_repondant', 'nom_resp', 'sexe_resp', 'adresse_resp', 'niveau_instruction_resp', 'tel_principal_resp', 'tel_secondaire_resp', 'email_resp', 'statut_foncier_resp', 'nom_org', 'type_org', 'type_org_autres', 'effectif_membres', 'nb_femmes', 'nb_hommes', 'date_creation_org', 'num_immatriculation', 'date_immatriculation_org', 'adresse_siege_org', 'gps_org', 'gps_org_lat', 'gps_org_lon', 'gps_org_alt', 'gps_org_prec', 'email_org', 'statut_famille_org', 'nom_org_communale', 'nom_org_prefectorale', 'nom_union_famille', 'vol_prod_plants', 'varietes_mangue', 'varietes_mangue_autres', 'variete_mangue_dom', 'variete_mangue_dom_autres', 'autres_prods_pepiniere', 'nom_resp_prod', 'sexe_resp_prod', 'adresse_resp_prod', 'niveau_instruction_resp_prod', 'tel_principal_resp_prod', 'tel_secondaire_resp_prod', 'email_resp_prod', 'statut_foncier_resp_prod', 'nom_org_prod', 'type_org_prod', 'effectif_membres_prod', 'nb_femmes_prod', 'nb_hommes_prod', 'date_creation_org_prod', 'num_immatriculation_prod', 'date_immatriculation_org_prod', 'adresse_siege_org_prod', 'gps_org_prod', 'gps_org_prod_lat', 'gps_org_prod_lon', 'gps_org_prod_alt', 'gps_org_prod_prec', 'email_org_prod', 'statut_famille_org_prod', 'nom_org_communale_prod', 'nom_org_prefectorale_prod', 'nom_union_famille_prod', 'superficie_mangue_org', 'nb_plants_manguiers', 'varietes_mangue_prod', 'varietes_mangue_prod_autres', 'variete_mangue_dom_prod', 'variete_mangue_dom_prod_autres', 'vol_prod_mangue', 'autres_prods_mangue', 'nom_resp_ent', 'sexe_resp_ent', 'adresse_resp_ent', 'niveau_instruction_resp_ent', 'tel_principal_resp_ent', 'tel_secondaire_resp_ent', 'email_resp_ent', 'statut_foncier_resp_ent', 'nom_ent', 'statut_juridique_ent', 'statut_juridique_ent_autres', 'effectif_personnel_ent', 'nb_femmes_ent', 'nb_hommes_ent', 'date_creation_ent', 'num_immatriculation_ent', 'date_immatriculation_ent', 'adresse_siege_ent', 'gps_ent', 'gps_ent_lat', 'gps_ent_lon', 'gps_ent_alt', 'gps_ent_prec', 'email_ent', 'statut_famille_ent', 'statut_foncier_unite', 'produits_derives', 'produits_derives_autres', 'produit_derive_dom', 'produit_derive_dom_autres', 'vol_achats', 'vol_ventes', 'type_certif', 'organisme_certif', 'autres_produits_ent', 'tel_secondaire_repondant_alt', 'tel_principal_resp_alt_3', 'tel_secondaire_resp_alt_3', 'superficie_mangue_membres', 'tel_principal_resp_alt_4', 'tel_secondaire_resp_alt_4', 'produits_transformes', 'vol_transforme', 'vol_ventes_derives', 'autres_prods_ent']

In [74]:
colonnes_a_fusionner_mangue = {
    # --- INFOS RÉPONDANT ---
    'repondant_tel_secondaire_unique': ['tel_secondaire_repondant', 'tel_secondaire_repondant_alt'],

    # --- INFOS RESPONSABLE ---
    'resp_nom_unique': ['nom_resp', 'nom_resp_prod', 'nom_resp_ent'],
    'resp_sexe_unique': ['sexe_resp', 'sexe_resp_prod', 'sexe_resp_ent'],
    'resp_adresse_unique': ['adresse_resp', 'adresse_resp_prod', 'adresse_resp_ent'],
    'resp_niveau_instruction_unique': ['niveau_instruction_resp', 'niveau_instruction_resp_prod', 'niveau_instruction_resp_ent'],
    'resp_tel_principal_unique': ['tel_principal_resp', 'tel_principal_resp_prod', 'tel_principal_resp_ent', 'tel_principal_resp_alt_3', 'tel_principal_resp_alt_4'],
    'resp_tel_secondaire_unique': ['tel_secondaire_resp', 'tel_secondaire_resp_prod', 'tel_secondaire_resp_ent', 'tel_secondaire_resp_alt_3', 'tel_secondaire_resp_alt_4'],
    'resp_email_unique': ['email_resp', 'email_resp_prod', 'email_resp_ent'],
    'resp_statut_foncier_unique': ['statut_foncier_resp', 'statut_foncier_resp_prod', 'statut_foncier_resp_ent'],

    # --- INFOS ENTITÉ ---
    'entite_nom_unique': ['nom_org', 'nom_org_prod', 'nom_ent'],
    'entite_type_unique': ['type_org', 'type_org_prod', 'statut_juridique_ent'],
    'entite_effectif_total_unique': ['effectif_membres', 'effectif_membres_prod', 'effectif_personnel_ent'],
    'entite_nb_femmes_unique': ['nb_femmes', 'nb_femmes_prod', 'nb_femmes_ent'],
    'entite_nb_hommes_unique': ['nb_hommes', 'nb_hommes_prod', 'nb_hommes_ent'],
    'entite_date_creation_unique': ['date_creation_org', 'date_creation_org_prod', 'date_creation_ent'],
    'entite_num_immatriculation_unique': ['num_immatriculation', 'num_immatriculation_prod', 'num_immatriculation_ent'],
    'entite_date_immatriculation_unique': ['date_immatriculation_org', 'date_immatriculation_org_prod', 'date_immatriculation_ent'],
    'entite_adresse_siege_unique': ['adresse_siege_org', 'adresse_siege_org_prod', 'adresse_siege_ent'],
    'entite_email_unique': ['email_org', 'email_org_prod', 'email_ent'],
    'entite_statut_famille_unique': ['statut_famille_org', 'statut_famille_org_prod', 'statut_famille_ent'],

    # --- INFOS GPS ---
    'gps_unique': ['gps_org', 'gps_org_prod', 'gps_ent'],
    'gps_lat_unique': ['gps_org_lat', 'gps_org_prod_lat', 'gps_ent_lat'],
    'gps_lon_unique': ['gps_org_lon', 'gps_org_prod_lon', 'gps_ent_lon'],
    'gps_alt_unique': ['gps_org_alt', 'gps_org_prod_alt', 'gps_ent_alt'],
    'gps_prec_unique': ['gps_org_prec', 'gps_org_prod_prec', 'gps_ent_prec'],

    # --- APPARTENANCE FAÎTIÈRES ---
    'nom_org_communale_unique': ['nom_org_communale', 'nom_org_communale_prod'],
    'nom_org_prefectorale_unique': ['nom_org_prefectorale', 'nom_org_prefectorale_prod'],
    'nom_union_famille_unique': ['nom_union_famille', 'nom_union_famille_prod'],

    # --- VARIABLES MANGUE SPÉCIFIQUES ---
    'varietes_mangue_unique': ['varietes_mangue', 'varietes_mangue_prod'],
    'variete_mangue_dom_unique': ['variete_mangue_dom', 'variete_mangue_dom_prod'],
    'varietes_mangue_autres_unique': ['varietes_mangue_autres', 'varietes_mangue_prod_autres'],
    
    # Fusionner les "Autres variétés dominantes"
    'variete_mangue_dom_autres_unique': ['variete_mangue_dom_autres', 'variete_mangue_dom_prod_autres']
}

def fusionner_col(df, dictionnaire):
    for base_final, liste_colonnes in dictionnaire.items():
        df[base_final] = df[liste_colonnes[0]]
        for liste_actuelle in liste_colonnes[1:]:
            df[base_final] = df[base_final].fillna(df[liste_actuelle])
    return df
df = fusionner_col(df,colonnes_a_fusionner_mangue)
df.head()

C:\Users\DELL\AppData\Local\Temp\ipykernel_39244\2786530732.py:53: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[base_final] = df[base_final].fillna(df[liste_actuelle])

,date_enquete,nom_enqueteur,village,canton,region,type_acteur,nom_repondant,sexe_repondant,niveau_instruction_repondant,tel_principal_repondant,...,gps_lon_unique,gps_alt_unique,gps_prec_unique,nom_org_communale_unique,nom_org_prefectorale_unique,nom_union_famille_unique,varietes_mangue_unique,variete_mangue_dom_unique,varietes_mangue_autres_unique,variete_mangue_dom_autres_unique
0,2026-03-05,Doumougue daminsete,Namouk,Tamongue,Savane,Producteurs,Lare gani,Homme,Aucun,93145658,...,0.225650,130.9,5.00,Cantonale,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-05,Doumougue daminsete,Namouk,Tamongue,Savanes,Producteurs,Kombate limanguedame,Homme,Aucun,71490229,...,0.224907,159.4,4.94,Saanatuon man communame,Saanatuon man,Polingbo,NaN,NaN,NaN,NaN
2,2026-03-09,Doumougue daminsete,Namouk,Tamongue,Savanes,Producteurs,Lare noaka,Homme,Aucun,93149192,...,0.225965,165.7,4.74,Communale,Saanatuon man,Polingbo,NaN,NaN,NaN,NaN
3,2026-03-09,Doumougue damonsete,Namoik,Tamongue,Savanes,Producteurs,Doumougue daminsete,Homme,Primaire,97340009,...,0.225977,179.3,4.98,Polingbo,Saanatounn man,Polingbo,NaN,NaN,NaN,NaN
4,2026-03-16,Doumougue daminsete,Nayargue,Tamongue,Savanes,Producteurs,Kolani poukinin,Homme,Aucun,90606437,...,0.165078,213.7,4.82,Cantonale,Polingbo,Polingbo,Eldonne Smith,Eldonne,NaN,NaN

In [75]:
liste_supprimer = []

for ancienne_liste in colonnes_a_fusionner_mangue.values():
    liste_supprimer.extend(ancienne_liste)

# La modification clé est ici : "df = ..."
df = df.drop(columns=liste_supprimer)

df.head()

,date_enquete,nom_enqueteur,village,canton,region,type_acteur,nom_repondant,sexe_repondant,niveau_instruction_repondant,tel_principal_repondant,...,gps_lon_unique,gps_alt_unique,gps_prec_unique,nom_org_communale_unique,nom_org_prefectorale_unique,nom_union_famille_unique,varietes_mangue_unique,variete_mangue_dom_unique,varietes_mangue_autres_unique,variete_mangue_dom_autres_unique
0,2026-03-05,Doumougue daminsete,Namouk,Tamongue,Savane,Producteurs,Lare gani,Homme,Aucun,93145658,...,0.225650,130.9,5.00,Cantonale,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-03-05,Doumougue daminsete,Namouk,Tamongue,Savanes,Producteurs,Kombate limanguedame,Homme,Aucun,71490229,...,0.224907,159.4,4.94,Saanatuon man communame,Saanatuon man,Polingbo,NaN,NaN,NaN,NaN
2,2026-03-09,Doumougue daminsete,Namouk,Tamongue,Savanes,Producteurs,Lare noaka,Homme,Aucun,93149192,...,0.225965,165.7,4.74,Communale,Saanatuon man,Polingbo,NaN,NaN,NaN,NaN
3,2026-03-09,Doumougue damonsete,Namoik,Tamongue,Savanes,Producteurs,Doumougue daminsete,Homme,Primaire,97340009,...,0.225977,179.3,4.98,Polingbo,Saanatounn man,Polingbo,NaN,NaN,NaN,NaN
4,2026-03-16,Doumougue daminsete,Nayargue,Tamongue,Savanes,Producteurs,Kolani poukinin,Homme,Aucun,90606437,...,0.165078,213.7,4.82,Cantonale,Polingbo,Polingbo,Eldonne Smith,Eldonne,NaN,NaN

In [76]:
print(df['region'].value_counts())

region
Kara              156
Plateau Ouest      66
Centrale           51
Plateaux           25
MARITIME           19
Maritime           10
Kara                8
Plateau             7
Plateau x           6
Savanes             6
Plateau x           5
Plateau             4
Plateau Ouest       2
Plateaux            2
Savane              1
 Savane             1
Sotouboua           1
Akplolo             1
Name: count, dtype: int64

In [77]:
df['region']=df['region'].str.strip().str.upper()

nettoyage_regions = {
    # --- KARA ---
    'KARA': 'KARA',
    
    # --- PLATEAUX ---
    'PLATEAU OUEST': 'PLATEAUX',
    'PLATEAUX': 'PLATEAUX',
    'PLATEAU': 'PLATEAUX',
    'PLATEAU X': 'PLATEAUX',
    'AKPLOLO': 'PLATEAUX',
    
    # --- MARITIME ---
    'MARITIME': 'MARITIME',
    
    # --- CENTRALE ---
    'CENTRALE': 'CENTRALE',
    'SOTOUBOUA': 'CENTRALE',
    
    # --- SAVANES ---
    'SAVANES': 'SAVANES',
    'SAVANE': 'SAVANES'
}

df['region'] = df['region'].replace(nettoyage_regions)
print(df['region'].value_counts())

region
KARA        164
PLATEAUX    118
CENTRALE     52
MARITIME     29
SAVANES       8
Name: count, dtype: int64

In [78]:
# On remplace le texte "_final" par "rien du tout" (une chaîne de caractères vide '')
df.columns = df.columns.str.replace('_unique', '')

# On affiche le résultat pour admirer le travail !
print(df.columns.tolist())

['date_enquete', 'nom_enqueteur', 'village', 'canton', 'region', 'type_acteur', 'nom_repondant', 'sexe_repondant', 'niveau_instruction_repondant', 'tel_principal_repondant', 'email_repondant', 'poste_repondant', 'type_org_autres', 'vol_prod_plants', 'autres_prods_pepiniere', 'superficie_mangue_org', 'nb_plants_manguiers', 'vol_prod_mangue', 'autres_prods_mangue', 'statut_juridique_ent_autres', 'statut_foncier_unite', 'produits_derives', 'produits_derives_autres', 'produit_derive_dom', 'produit_derive_dom_autres', 'vol_achats', 'vol_ventes', 'type_certif', 'organisme_certif', 'autres_produits_ent', 'superficie_mangue_membres', 'produits_transformes', 'vol_transforme', 'vol_ventes_derives', 'autres_prods_ent', 'repondant_tel_secondaire', 'resp_nom', 'resp_sexe', 'resp_adresse', 'resp_niveau_instruction', 'resp_tel_principal', 'resp_tel_secondaire', 'resp_email', 'resp_statut_foncier', 'entite_nom', 'entite_type', 'entite_effectif_total', 'entite_nb_femmes', 'entite_nb_hommes', 'entite_date_creation', 'entite_num_immatriculation', 'entite_date_immatriculation', 'entite_adresse_siege', 'entite_email', 'entite_statut_famille', 'gps', 'gps_lat', 'gps_lon', 'gps_alt', 'gps_prec', 'nom_org_communale', 'nom_org_prefectorale', 'nom_union_famille', 'varietes_mangue', 'variete_mangue_dom', 'varietes_mangue_autres', 'variete_mangue_dom_autres']

In [80]:
for col in df.columns:
    print(f'____{col}____')
    print(df[col].value_counts())
    print('\n')

____date_enquete____
date_enquete
2026-04-21    52
2026-04-22    35
2026-04-27    27
2026-05-13    22
2026-05-16    18
2026-05-04    18
2026-04-24    17
2026-04-15    15
2026-04-16    12
2026-05-12    11
2026-04-20    11
2026-04-30    10
2026-04-25    10
2026-05-03     9
2026-04-29     9
2026-04-13     9
2026-05-14     8
2026-04-28     8
2026-05-06     7
2026-04-26     6
2026-04-14     6
2026-04-23     6
2026-05-07     5
2026-05-05     5
2026-05-15     4
2026-04-09     3
2026-04-02     3
2026-04-17     3
2026-04-18     2
2026-03-09     2
2026-04-04     2
2026-04-10     2
2026-03-05     2
2026-04-05     2
2026-03-16     1
2026-03-20     1
2026-04-11     1
2017-11-23     1
2026-04-03     1
2026-04-08     1
2029-02-27     1
2026-03-02     1
2026-02-10     1
2026-02-17     1
Name: count, dtype: int64


____nom_enqueteur____
nom_enqueteur
ABI Essoyomewè               146
Dzah Yawo Amedzeafe           65
AKABA Essodina                25
ADINDA-AKPO A. Affo           25
Amegan komla fafali           19
Tolo djamiou                  12
LAWSON TOGLA LATÉ VÉVÉ         9
ABI Essoyomewè                 8
ADEGNON Yao Gabriel            7
LAWSON-TOGLA LATÉ VÉVÉ         7
Assogba Salam                  6
Tolo  djamiou                  4
BODI KAGO Marouane             4
ABI Essoyomewe                 3
Assogba Salam                  3
Doumougue daminsete            3
Tolo. Djamiou                  2
ADINDA-AKPO A.Affo             2
DANDJA Namtiebe                2
Dzah Yawo Amedzeafe            2
Doumougue damonsete            1
Doumougue  daminsete           1
AGBOLETE KOMLAGAN JEAN         1
Tolo djamiou                   1
Tolo  djamiou                  1
LARE Yendouname                1
Ado  hilary                    1
Hilary ADO                     1
Tolo djamiou..                 1
Dzah                           1
Assogba salame                 1
Mamah yakoubou                 1
ADEGNON                        1
LAWSON TOGLA LATÉ VÉVÉ.        1
LAWSON-TOGLA LATÉ              1
LAWSON-TOGLA  LATÉ VÉVÉ        1
LAWSON TOGLA LATÉ VÉVÉ hu      1
Name: count, dtype: int64


____village____
village
Lavie Apedome    57
Tchikawa         51
Kpinzidè         18
Agan             18
Kiakou           16
                 ..
GAPÉ-VAKPO        1
Vo                1
GLETO             1
AKPAKA COPÉ       1
AGOME             1
Name: count, Length: 85, dtype: int64


____canton____
canton
Lavie Apedome    59
Lama-tessi       50
Kétao            28
Kpinzidè         25
Moretan          21
                 ..
?n??              1
Vo                1
LILI KOPÉ         1
?                 1
ZIO CENTRE        1
Name: count, Length: 68, dtype: int64


____region____
region
KARA        164
PLATEAUX    118
CENTRALE     52
MARITIME     29
SAVANES       8
Name: count, dtype: int64


____type_acteur____
type_acteur
Producteurs                        279
Pépiniéristes                       78
Transformateurs  - Exportateurs     14
Name: count, dtype: int64


____nom_repondant____
nom_repondant
HODIKU koffi                  6
ATOKITETO Atokiyï             2
BISSOSSOUWE Petemapata        2
BOUDOU Anabigué               2
ABALO Kodabalo                2
                             ..
Tchao Didie                   1
Kouyakoudili  Koumberabalo    1
Kao tchaa                     1
ATIPATÉ.    YVE               1
SODOLI   KODJO                1
Name: count, Length: 362, dtype: int64


____sexe_repondant____
sexe_repondant
Homme    315
Femme     56
Name: count, dtype: int64


____niveau_instruction_repondant____
niveau_instruction_repondant
Collège             152
Primaire             92
Lycée                64
Aucun                44
Université           17
Ecole coranique       2
Name: count, dtype: int64


____tel_principal_repondant____
tel_principal_repondant
90357974    6
12345678    3
92324002    2
90961451    2
90941864    2
           ..
90074047    1
92503022    1
98663019    1
98532300    1
97956537    1
Name: count, Length: 352, dtype: int64


____email_repondant____
email_repondant
Aklessolabo7@gmel.com      1
toihlucien@gmail.com       1
solangeadjim3@gmail.com    1
abouolibier53@gmail.com    1
oladeawlui08@gmail.com     1
adjialiou72@gmail.com      1
martindzah75@gmail.com     1
saibouadam733@gmail.com    1
Tolodjamiou17              1
@72alassan                 1
dearofbeni@gmail.com       1
Name: count, dtype: int64


____poste_repondant____
poste_repondant
Responsable               212
Membre                     21
Propriétaire               18
Président                  12
Président                  11
GÉRANT                      9
Responsable                 9
President                   8
Producteur                  6
RESPONSABLE                 5
President                   5
Directeur                   4
Secrétaire                  4
Conseiller                  2
Gérant                      2
PROPRIÉTAIRE                2
Secretaire                  2
Propriétair                 1
Le directeur                1
Pépiniériste                1
Konseiller                  1
Producteur                  1
Secrétaire                  1
Coordinateur                1
Président/individuel /      1
Resposable                  1
President de l'Union        1
Presidente                  1
Assistant                   1
Trésorier                   1
Présidente                  1
Membre de famille           1
OUVRIER                     1
?                           1
GÉRANTE                     1
Name: count, dtype: int64


____type_org_autres____
Series([], Name: count, dtype: int64)


____vol_prod_plants____
vol_prod_plants
10000.00    10
0.50        10
5000.00     10
5.00         5
3000.00      5
1.00         5
1000.00      3
6000.00      3
200.00       3
25.00        2
500.00       2
0.75         2
100.00       2
8000.00      2
2.00         1
2.25         1
25000.00     1
1.50         1
20.00        1
30.00        1
1500.00      1
2500.00      1
3.00         1
12000.00     1
7000.00      1
2000.00      1
50.00        1
1555.00      1
Name: count, dtype: int64


____autres_prods_pepiniere____
autres_prods_pepiniere
Anacarde                                                                                                      8
Anacarde                                                                                                      5
Anacarde palmier                                                                                              3
Palmier à huile arbres fruitiers et forestiers noix de coco orange greffe et ordinaire et autres              2
Citron greffe/                                                                                                1
                                                                                                             ..
Anacardier                                                                                                    1
FLEURS ORNEMENTALES - CITRUS - PAPAYER  - COCOTIER- COROSSOLIER -  PLANTES DE REBOISEMENT- PALMIER À HUILE    1
Moringa, Gmelina, Néré, Khaya, Baobab                                                                         1
ESSENSES FORESTIÈRES    /   AGRUMES / PLANTES OLEAGINEUSES   /  AUTRES FRUITIERS  PLANTES ORNEMENTALES        1
ESSENSES FORESTIÈRES  /  CITRUS   /  PLANTES OLEAGINEUSES   /   PLANTES ORNEMENTALES....                      1
Name: count, Length: 61, dtype: int64


____superficie_mangue_org____
superficie_mangue_org
6.250000e-02    39
1.250000e-01    33
1.000000e+00    27
5.000000e-01    24
2.500000e+01    22
6.250000e-01    20
2.000000e+00    15
5.000000e+00    14
2.500000e-01    12
3.000000e+00     6
1.500000e+00     5
5.000000e+01     4
7.500000e-01     3
4.000000e+00     2
1.000000e+02     2
2.500000e+00     2
1.880000e-01     2
1.600000e+01     1
2.000000e+01     1
8.500000e+01     1
6.000000e+01     1
1.200000e+02     1
7.000000e+00     1
9.682561e+07     1
1.875000e-01     1
3.400000e+01     1
1.800000e-01     1
1.750000e+00     1
8.125000e-01     1
3.200000e-01     1
1.500000e+01     1
Name: count, dtype: int64


____nb_plants_manguiers____
nb_plants_manguiers
5.0       23
6.0       19
4.0       18
50.0      15
100.0     14
3.0       12
8.0       11
10.0      11
200.0      7
9.0        7
7.0        7
2.0        6
20.0       4
15.0       4
500.0      4
250.0      3
24.0       3
80.0       3
1.0        3
300.0      2
30.0       2
11.0       2
12.0       2
25.0       2
17.0       2
102.0      1
68.0       1
338.0      1
360.0      1
21.0       1
150.0      1
400.0      1
52.0       1
180.0      1
700.0      1
2470.0     1
51.0       1
49.0       1
38.0       1
13.0       1
67.0       1
144.0      1
47.0       1
16.0       1
14.0       1
40.0       1
18.0       1
46.0       1
75.0       1
2500.0     1
Name: count, dtype: int64


____vol_prod_mangue____
vol_prod_mangue
1.00      24
2.00      22
5.00       9
10.00      9
4.00       5
0.50       5
3.00       5
6.00       5
40.00      3
20.00      3
7.00       2
8.00       2
30.00      2
22.00      1
25.00      1
50.00      1
16.00      1
0.15       1
0.20       1
0.85       1
200.00     1
1.50       1
53.00      1
0.60       1
0.30       1
26.00      1
17.00      1
45.00      1
Name: count, dtype: int64


____autres_prods_mangue____
autres_prods_mangue
Anarcarde                                58
Palmier à huile                          12
Anacarde                                  8
Anacard                                   6
Anarcarde, Palmier à huile                6
                                         ..
CITRON. /  MAÏS   /    HARICOTS           1
CITRUS                                    1
ORANGE                                    1
RIZ  -  MAÏS                              1
CULTURE VIVRIÈRE   ( MAÏS   MANIOC  )     1
Name: count, Length: 104, dtype: int64


____statut_juridique_ent_autres____
Series([], Name: count, dtype: int64)


____statut_foncier_unite____
statut_foncier_unite
Locataire / Bail    9
Propriétaire        5
Name: count, dtype: int64


____produits_derives____
produits_derives
Autres                    7
Jus de mangue             1
Autres  Jus de mangue     1
Name: count, dtype: int64


____produits_derives_autres____
produits_derives_autres
FRUIT FRAIS    1
Name: count, dtype: int64


____produit_derive_dom____
produit_derive_dom
Autres (à préciser)    3
Name: count, dtype: int64


____produit_derive_dom_autres____
produit_derive_dom_autres
FRUIT FRAIS    1
Name: count, dtype: int64


____vol_achats____
vol_achats
1.50     2
6.00     2
18.20    1
40.00    1
26.00    1
22.75    1
1.20     1
5.50     1
4.50     1
4.00     1
3.00     1
60.00    1
Name: count, dtype: int64


____vol_ventes____
vol_ventes
1.00      3
100.00    1
5.20      1
20.80     1
15.15     1
5.00      1
4.50      1
4.00      1
3.80      1
5.50      1
1.60      1
55.00     1
Name: count, dtype: int64


____type_certif____
Series([], Name: count, dtype: int64)


____organisme_certif____
organisme_certif
Bio SPG    1
Name: count, dtype: int64


____autres_produits_ent____
autres_produits_ent
Manioc                                                                       2
Orange banane  avocat                                                        1
PAPAYE  , ANANAS  ,  PASTÈQUE  MELON ,  MAÏS FRAIS                           1
ANANAS-CARAMBOLE- PASTÈQUE-ORANGE- MAÏS FRAIS  - MANIOC                      1
Tous les fruits et le jus de riz                                             1
ANANAS-ORANGE- BANANE- AVOCAT- POMME- CLÉMENTINE- RAISIN - POMME DE TERRE    1
Maïs, manioc, coco                                                           1
Pastèque et fruits, pépinière de coco                                        1
Manioc, maïs, huile rouge                                                    1
Manioc, Tomates, Oignons                                                     1
ORANGE/  LÉGUME   /  MANIOC   / NOIX DE PALME                                1
AVOCAT- ANANAS-ORANGE-PAPAYE-CARAMBOLE                                       1
ORANGE/ CITRON /BANANE PLATAIN/ ANANAS/ LÉGUMES                              1
Name: count, dtype: int64


____superficie_mangue_membres____
Series([], Name: count, dtype: int64)


____produits_transformes____
Series([], Name: count, dtype: int64)


____vol_transforme____
Series([], Name: count, dtype: int64)


____vol_ventes_derives____
Series([], Name: count, dtype: int64)


____autres_prods_ent____
Series([], Name: count, dtype: int64)


____repondant_tel_secondaire____
repondant_tel_secondaire
96426282.0    2
93540538.0    1
90944133.0    1
98309410.0    1
96810552.0    1
             ..
87654321.0    1
93136684.0    1
92261411.0    1
71185745.0    1
79718656.0    1
Name: count, Length: 96, dtype: int64


____resp_nom____
resp_nom
HODIKU koffi              2
ATOKITETO Atokiyï         2
BOUDOU Anabigué           2
BISSOSSOUWE Petemapata    2
ABALO Kodabalo            2
                         ..
Akakpo soliou             1
Edikou bassirou           1
Akakpo fitore             1
Abilou karimou            1
TCHASSANTI Salifou        1
Name: count, Length: 345, dtype: int64


____resp_sexe____
resp_sexe
Homme    312
Femme     59
Name: count, dtype: int64


____resp_adresse____
resp_adresse
Binah, Lama-tessi, Tchikawa, Kpelessida                          31
Kloto Commune kloto 2 Lavie                                      18
Binah, Lama-tessi, Tchikawa, Tchikawa                            13
Binah, Lama-tessi, Tchikawa, Tchikawa                             9
Binah, Kétao, Kadjanga, Kpizidè                                   8
                                                                 ..
ZIO   /   TSEVIÉ /   DJIDJOLE   /  DERRIÈRE BRIGADE MOTORISÉE     1
CANADA                                                            1
ZIO.   /   DAVIÉ.    /   DAVIÉ   /  OFED                          1
. AKOTEM BLESSING                                                 1
PRÉFECTURE DU GOLFE    /   LOMÉ    /   ATIÉGOU                    1
Name: count, Length: 160, dtype: int64


____resp_niveau_instruction____
resp_niveau_instruction
Collège             140
Primaire             84
Lycée                59
Aucun                43
Université           23
Ecole coranique       2
Name: count, dtype: int64


____resp_tel_principal____
resp_tel_principal
12345678.0    5
90935974.0    4
98786866.0    2
90239380.0    2
90961451.0    2
             ..
92127644.0    1
90169660.0    1
93560893.0    1
91968321.0    1
92953593.0    1
Name: count, Length: 351, dtype: int64


____resp_tel_secondaire____
resp_tel_secondaire
96426282.0    2
90944133.0    1
98309410.0    1
96810552.0    1
99373182.0    1
             ..
99570185.0    1
92342433.0    1
87654321.0    1
71185745.0    1
79718656.0    1
Name: count, Length: 87, dtype: int64


____resp_email____
resp_email
aklessolabo7@gmel.com      1
toihlucien@gmail.com       1
solangeadjim3@gmail.com    1
abouolibier53@gmail.com    1
oladeawlui08@gmail.com     1
martindzah75@gmail.com     1
@72alassan                 1
dearofbeni@gmail.com       1
Name: count, dtype: int64


____resp_statut_foncier____
resp_statut_foncier
Propriétaire        350
Locataire / bail     19
Name: count, dtype: int64


____entite_nom____
entite_nom
SCOOPS ISRAËL    16
ASSILEASSIME     10
N A               9
Producteur        6
GAJAK             4
                 ..
Oko greffé        1
Néan              1
Kpémé             1
Famille YAKAS     1
?                 1
Name: count, Length: 131, dtype: int64


____entite_type____
entite_type
Individuel                                             285
Société coopérative simplifiée (SCOOPS)                 41
Etablissement  ETS                                      24
Groupement                                              15
Groupe de solidarité                                     2
SARL                                                     1
Coopérative avec conseil d'administration (COOP CA)      1
Association                                              1
Autres (préciser)                                        1
Name: count, dtype: int64


____entite_effectif_total____
entite_effectif_total
1.0      272
17.0      17
5.0       14
7.0        9
6.0        8
3.0        8
0.0        8
8.0        7
10.0       6
2.0        6
4.0        3
11.0       3
9.0        1
15.0       1
16.0       1
20.0       1
21.0       1
12.0       1
93.0       1
50.0       1
27.0       1
137.0      1
Name: count, dtype: int64


____entite_nb_femmes____
entite_nb_femmes
0.0      256
1.0       53
2.0       38
3.0        8
4.0        7
50.0       2
5.0        2
8.0        1
12.0       1
6.0        1
11.0       1
133.0      1
Name: count, dtype: int64


____entite_nb_hommes____
entite_nb_hommes
1.0     238
0.0      51
15.0     17
4.0      13
3.0      13
5.0      12
2.0       8
8.0       5
6.0       4
7.0       3
16.0      2
11.0      1
19.0      1
12.0      1
43.0      1
10.0      1
Name: count, dtype: int64


____entite_date_creation____
entite_date_creation
2019-04-15    14
1990-04-30    11
2022-06-30    10
2019-04-30     6
1980-04-30     6
              ..
1995-06-05     1
2014-02-05     1
1986-04-14     1
1990-04-14     1
2024-06-01     1
Name: count, Length: 261, dtype: int64


____entite_num_immatriculation____
entite_num_immatriculation
SCS 4698/2020/MAEDR/SG/DFDTOPA     7
N A                                4
SCS 4698/2020/MAEDR SG DFDTOPA     2
SCS4698/2020/MAEDR/SG/DFDTOPA      2
N*scs01461\2017                    1
SCS 7119/2023/MAEDR/SG/DFDTOPA     1
Na                                 1
N'scs01461/ 2017 ,                 1
5458178                            1
SCS00124/2012/MAEP/SG/DPCA/DIR     1
4523                               1
SCS 4698/2020/MAEDR/ SG/DFDTOPA    1
SCS 4698/2020/ MAEDR/SG/DFDTOPA    1
SCS4698/2020/MAEDR SG DFDTOPA      1
SCS 4698/2020/MAEDR/DFDTOPA        1
SCS 4698/2020/MAEDR/ SG DFDTOPA    1
BM                                 1
Name: count, dtype: int64


____entite_date_immatriculation____
entite_date_immatriculation
2020-11-30    17
2017-12-26     1
2027-03-27     1
2025-06-15     1
2017-12-28     1
2024-03-20     1
1997-06-01     1
2012-12-31     1
2023-07-17     1
2019-02-12     1
2019-01-16     1
2026-05-06     1
2030-04-30     1
Name: count, dtype: int64


____entite_adresse_siege____
entite_adresse_siege
Tchikawa                                                   53
Lavie Huime                                                25
Lavie Apedome                                              21
Kadjanga                                                   14
Atakpame                                                   14
                                                           ..
ZIO 4   /  GAPÉ   /   KOULI  /   KOULI- BELLA BELLOW        1
AD                                                          1
Gvjh                                                        1
?                                                           1
ZIO 1.  /  TSEVIÉ   /   LILIKOPÉ   /    TOGO - CARRIÈRE     1
Name: count, Length: 122, dtype: int64


____entite_email____
entite_email
N/a                        2
Agan                       1
Ferme OREMI                1
Sotouboua                  1
telright01gmail.com        1
abouolibier53@gmail.com    1
oladeawlui08@gmail.com     1
'NA                        1
BP:34                      1
@23mamah                   1
Name: count, dtype: int64


____entite_statut_famille____
entite_statut_famille
Membre actif        211
Membre potentiel    150
Membre inactif       10
Name: count, dtype: int64


____gps____
gps
7.0118948 0.6783424 0.0 500.0                  7
6.9934565 0.6555176 0.0 400.0                  3
6.8714836 0.7876061 0.0 899.999                3
6.9367966 0.8310371 0.0 4000.0                 3
7.0125618 0.6816041 0.0 699.999                2
                                              ..
7.0213352 0.6950379 283.9000244140625 2.152    1
9.6602007 1.3409133 245.538 2.112              1
9.759836 1.2476891 4474.95 1.948               1
7.0212719 0.6950217 283.9000244140625 2.399    1
9.7125411 1.289194 429.842 1.566               1

In [81]:
import pandas as pd

# 1. Uniformisation de base
df['nom_enqueteur'] = df['nom_enqueteur'].astype(str).str.replace('"', '', regex=False)
df['nom_enqueteur'] = df['nom_enqueteur'].str.strip().str.upper()

# 2. Dictionnaire de corrections Regex adapté à cette 4ème liste
corrections_enqueteurs_4 = {
    r'^.*ABI.*$': 'ABI ESSOYOMEWÈ',
    r'^.*DZAH.*$': 'DZAH YAWO AMEDZEAFE',
    r'^.*AKABA.*$': 'AKABA ESSODINA',
    r'^.*ADINDA.*$': 'ADINDA-AKPO A. AFFO',
    r'^.*AMEGAN.*$': 'AMEGAN KOMLA FAFALI',
    r'^.*TOLO.*$': 'TOLO DJAMIOU',
    r'^.*LAWSON.*$': 'LAWSON-TOGLA LATÉ VÉVÉ',
    r'^.*ADEGNON.*$': 'ADEGNON YAO GABRIEL',
    r'^.*ASSOGBA.*$': 'ASSOGBA SALAM',
    r'^.*BODI.*$': 'BODI KAGO MAROUANE',
    r'^.*DOUMOUGUE.*$': 'DOUMOUGUE DAMINSETE',
    r'^.*DANDJA.*$': 'DANDJA NAMTIEBE',
    r'^.*AGBOLETE.*$': 'AGBOLETE KOMLAGAN JEAN',
    r'^.*LARE.*$': 'LARE YENDOUNAME',
    r'^.*ADO.*$': 'ADO HILARY',
    r'^.*MAMAH.*$': 'MAMAH YAKOUBOU'
}

# 3. Application du remplacement
df['nom_enqueteur'] = df['nom_enqueteur'].replace(corrections_enqueteurs_4, regex=True)

# 4. Vérification finale
print(df['nom_enqueteur'].value_counts())

nom_enqueteur
ABI ESSOYOMEWÈ            157
DZAH YAWO AMEDZEAFE        68
ADINDA-AKPO A. AFFO        27
AKABA ESSODINA             25
TOLO DJAMIOU               21
LAWSON-TOGLA LATÉ VÉVÉ     20
AMEGAN KOMLA FAFALI        19
ASSOGBA SALAM              10
ADEGNON YAO GABRIEL         8
DOUMOUGUE DAMINSETE         5
BODI KAGO MAROUANE          4
ADO HILARY                  2
DANDJA NAMTIEBE             2
LARE YENDOUNAME             1
AGBOLETE KOMLAGAN JEAN      1
MAMAH YAKOUBOU              1
Name: count, dtype: int64

In [82]:
df['date_enquete'] = pd.to_datetime(df['date_enquete'],errors = 'coerce')
df['date_enquete'] = df['date_enquete'].dt.date

print(df['date_enquete'].head())

0    2026-03-05
1    2026-03-05
2    2026-03-09
3    2026-03-09
4    2026-03-16
Name: date_enquete, dtype: object

In [84]:
# première lettre en majuscule et le reste en minuscule
colonne_a_convertir = ['village', 'canton','resp_adresse','nom_repondant']

# Boucle pour changer la première lettre
for col in colonne_a_convertir:
    df[col] = df[col].astype(str).str.capitalize()

df[colonne_a_convertir]=df[colonne_a_convertir].replace('Nan','')

In [85]:
# Sauvegarde en Excel
df.to_excel("Mangue_propre4.xlsx", index=False)