# Traitement de la base PRT

In [33]:
### importation des bibliothèque et importation de la base de donnée

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('prt.xlsx')
df.head()

,start,end,"Info : Cher(e) participant(e),Dans le cadre de cette enquête, des données personnelles seront collectées. Ces données serviront uniquement à l'actualisation de la base de données des familles membres de l'interprofession. Votre participation est volontaire et vous pouvez arrêter l’entretien à tout moment, sans aucune conséquence négative. Elles ne seront pas transmises à des tiers non impliqués dans l'activité.",Consentez-vous à la collecte et à l’utilisation de vos données comme décrit ci-dessus ?,Date de l’enquête :,Nom et prénoms de l’enquêteur :,Village de l'enquête :,Canton de l'enquête :,Région de l'enquête :,Type d'acteurs:,...,_uuid,_submission_time,_validation_status,_notes,_status,_submitted_by,__version__,_tags,meta/rootUuid,_index
0,2026-04-01 16:17:33.971,2026-04-02 14:54:40.331,NaN,"Oui, j’ai lu et compris la note d’information ...",2026-04-02,BADOHOUN amegno kossi,Sama copé,Gleï,Plateaux,Producteurs,...,346c9434-fe63-4d4a-9e37-2c3b908e4049,2026-04-02 17:30:10,NaN,NaN,submitted_via_web,interpro2025,vKyebBVmwJfELG4S4ijB5K,NaN,uuid:346c9434-fe63-4d4a-9e37-2c3b908e4049,1
1,2026-04-02 14:55:07.400,2026-04-02 15:07:22.548,NaN,"Oui, j’ai lu et compris la note d’information ...",2026-04-02,BADOHOUN amegno kossi,SAMA copé,Gleï,Plateaux,Producteurs,...,45a42083-fe2b-448a-a920-200db328ba05,2026-04-02 17:30:10,NaN,NaN,submitted_via_web,interpro2025,vKyebBVmwJfELG4S4ijB5K,NaN,uuid:45a42083-fe2b-448a-a920-200db328ba05,2
2,2026-04-02 15:07:42.075,2026-04-02 15:16:39.229,NaN,"Oui, j’ai lu et compris la note d’information ...",2026-04-02,BADOHOUN amegno kossi,SAMA copé,Gleï,Plateaux,Producteurs,...,8cf2541b-643d-405d-97a0-401b8e7aa427,2026-04-02 17:30:11,NaN,NaN,submitted_via_web,interpro2025,vKyebBVmwJfELG4S4ijB5K,NaN,uuid:8cf2541b-643d-405d-97a0-401b8e7aa427,3
3,2026-04-02 15:16:50.438,2026-04-02 15:24:53.936,NaN,"Oui, j’ai lu et compris la note d’information ...",2026-04-02,BADOHOUN amegno kossi,SAMA copé,Gleï,Plateaux,Producteurs,...,2d31a8ed-bda3-43e9-a9c0-f9199b773f1e,2026-04-02 17:30:11,NaN,NaN,submitted_via_web,interpro2025,vKyebBVmwJfELG4S4ijB5K,NaN,uuid:2d31a8ed-bda3-43e9-a9c0-f9199b773f1e,4
4,2026-04-02 15:25:38.923,2026-04-02 15:33:26.483,NaN,"Oui, j’ai lu et compris la note d’information ...",2026-04-02,BADOHOUN amegno kossi,SAMA copé,Gleï,Plateaux,Producteurs,...,63f3ebbc-58ff-4805-9d99-309d057a4f4e,2026-04-02 17:30:12,NaN,NaN,submitted_via_web,interpro2025,vKyebBVmwJfELG4S4ijB5K,NaN,uuid:63f3ebbc-58ff-4805-9d99-309d057a4f4e,5

In [34]:
print(df.columns.tolist())

['start', 'end', "Info : Cher(e) participant(e),Dans le cadre de cette enquête, des données personnelles seront collectées. Ces données serviront uniquement à l'actualisation de la base de données des familles membres de l'interprofession. Votre participation est volontaire et vous pouvez arrêter l’entretien à tout moment, sans aucune conséquence négative. Elles ne seront pas transmises à des tiers non impliqués dans l'activité. ", 'Consentez-vous à la collecte et à l’utilisation de vos données comme décrit ci-dessus ?', 'Date de l’enquête : ', 'Nom et prénoms de l’enquêteur : ', "Village de l'enquête : ", "Canton de l'enquête : ", "Région de l'enquête : ", "Type d'acteurs: ", 'Type de spéculation : ', 'Type de spéculation : /Manioc', 'Type de spéculation : /Igname', 'Type de spéculation : /Patate douce', 'Type de spéculation : /Souchet', 'Nom et prénoms du répondant ', 'Sexe du répondant  : ', 'Niveau instruction du répondant : ', 'Numéro de téléphone principal: ', 'Numéro de téléphone secondaire : ', 'Adresse électronique (mail): ', 'Poste occupé par le répondant  : ', 'Nom et prénoms du premier responsable', 'Sexe du premier responsable : ', 'Adresse complète du premier responsable : ', 'Niveau instruction du premier responsable  : ', 'Numéro de téléphone principal du premier responsable :  ', 'Numéro de téléphone secondaire du premier responsable :  ', 'Adresse électronique (mail) du premier responsable : ', 'Statut sur le plan foncier du premier responsable : ', "Nom de l'organisation de base / structure ", 'Type d’organisation / structure', 'Autres', 'Effectif des membres : ', 'Nombre de femmes : ', "Nombre d'hommes : ", "Date de création de l'organisation : ", "Numéro d'enregistrement / immatriculation : ", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : ', 'Adresse du siège de l’organisation : ', 'Coordonnées GPS du siège ou du premier responsable: ', '_Coordonnées GPS du siège ou du premier responsable: _latitude', '_Coordonnées GPS du siège ou du premier responsable: _longitude', '_Coordonnées GPS du siège ou du premier responsable: _altitude', '_Coordonnées GPS du siège ou du premier responsable: _precision', 'Adresse électronique de l’organisation à la base : ', 'Statut actuel de l’enquêté (organisation à la base) dans la famille : ', 'Nom de l’organisation communale / cantonale : ', 'Nom de l’organisation préfectorale :', "Nom de l'Union membre de la famille : ", 'Superficie totale moyenne emblavée annuellement par votre organisation pour la production de plantes à racines et à tubercules  ( en ha) :  ', 'Volume total moyen annuel de production de souchets pour votre organisation (en tonnes) : ', 'Volume total moyen annuel de production de manioc pour votre organisation ( nombre de boutures)) : ', 'Volume total moyen annuel de production de patates douces pour votre organisation ( nombre de lianes) : ', "Volume total moyen annuel de production d'ignames pour votre organisation ( nombre de semenceaux)) : ", 'Autres productions que vous effectuez à part les plantes à racines et à tubercules : ', 'Nom et prénoms du premier responsable.1', 'Sexe du premier responsable : .1', 'Adresse complète du premier responsable : .1', 'Niveau instruction du premier responsable  : .1', 'Numéro de téléphone principal du premier responsable :  .1', 'Numéro de téléphone secondaire du premier responsable :  .1', 'Adresse électronique (mail) du premier responsable : .1', 'Statut sur le plan foncier du premier responsable : .1', "Nom de l'organisation de base / structure .1", 'Type d’organisation / structure.1', 'Autres.1', 'Effectif des membres : .1', 'Nombre de femmes : .1', "Nombre d'hommes : .1", "Date de création de l'organisation : .1", "Numéro d'enregistrement / immatriculation : .1", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .1', 'Adresse du siège de l’organisation : .1', 'Coordonnées GPS du siège ou du premier responsable: .1', '_Coordonnées GPS du siège ou du premier responsable: _latitude.1', '_Coordonnées GPS du siège ou du premier responsable: _longitude.1', '_Coordonnées GPS du siège ou du premier responsable: _altitude.1', '_Coordonnées GPS du siège ou du premier responsable: _precision.1', 'Adresse électronique de l’organisation à la base : .1', 'Statut actuel de l’enquêté (organisation à la base) dans la famille : .1', 'Nom de l’organisation communale / cantonale : .1', 'Nom de l’organisation préfectorale :.1', "Nom de l'Union membre de la famille : .1", 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes racines et à tubercules  ( en ha) :  ', 'Volume total moyen annuel de production de plantes à racines et à tubercules  pour votre organisation ( en tonnes) : ', 'Autres productions que vous effectuez à part les plantes à racines et à tubercules : .1', 'Nom et prénoms du premier responsable.2', 'Sexe du premier responsable : .2', 'Adresse complète du premier responsable : .2', 'Niveau instruction du premier responsable  : .2', 'Numéro de téléphone principal du premier responsable :  .2', 'Numéro de téléphone secondaire du premier responsable :  .2', 'Adresse électronique (mail) du premier responsable : .2', 'Statut sur le plan foncier du premier responsable : .2', "Raison sociale de l'entreprise ", 'Statut juridique :', 'Autres: ', "Effectif des membres / personnels de l'entreprise : ", 'Nombre de femmes : .2', "Nombre d'hommes : .2", "Date de création de l'entreprise : ", "Numéro d'enregistrement / immatriculation : .2", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .2', 'Adresse du siège de l’entreprise: ', 'Coordonnées GPS : ', '_Coordonnées GPS : _latitude', '_Coordonnées GPS : _longitude', '_Coordonnées GPS : _altitude', '_Coordonnées GPS : _precision', 'Adresse électronique de l’entreprise : ', 'Statut actuel de l’enquêté (entreprise) dans la famille : ', "Statut sur le plan foncier (lieu d'installation de l'unité) ", 'Produits transformés à base de plantes à racines et tubercules  :', 'Produits transformés à base de manioc  :', 'Produits transformés à base de manioc  :/Gari ', 'Produits transformés à base de manioc  :/Tapioca', 'Produits transformés à base de manioc  :/Cosette de manioc', 'Produits transformés à base de manioc  :/Purée de manioc', 'Produits transformés à base de manioc  :/Amidon', 'Produits transformés à base de manioc  :/Ethanol de manioc', 'Produits transformés à base de manioc  :/Autres ', 'Produits transformés à base de manioc  :/Pate fermentée à base de manioc (Agbelima)', 'Autres ', "Volume total moyen annuel de produits transformé par l'entreprise (en tonnes) : ", "Volume moyen annuel de produits vendus  par l'entreprise (en tonnes) : ", 'Type de certification : ', "Nom de l'organisme certificateur :", "Nom de l'organisme certificateur :/CCPB", "Nom de l'organisme certificateur :/ECOCERT", "Nom de l'organisme certificateur :/SRS", "Nom de l'organisme certificateur :/ONECERT", "Nom de l'organisme certificateur :/CONTROL", "Nom de l'organisme certificateur :/UNION", "Nom de l'organisme certificateur :/CERES", "Nom de l'organisme certificateur :/Global Gap", "Nom de l'organisme certificateur :/Bio SPG", "Nom de l'organisme certificateur :/Global Gap.1", "Nom de l'organisme certificateur :/Bio SPG.1", 'Autres productions que vous effectuez à part les plantes à tubercules : ', 'Nom et prénoms du premier responsable.3', 'Sexe du premier responsable : .3', 'Adresse complète du premier responsable : .3', 'Niveau instruction du premier responsable  : .3', 'Numéro de téléphone principal du premier responsable :  .3', 'Numéro de téléphone secondaire du premier responsable :  .3', 'Adresse électronique (mail) du premier responsable : .3', 'Statut sur le plan foncier du premier responsable : .3', "Raison sociale de l'entreprise .1", 'Statut juridique :.1', 'Autres: .1', "Effectif des membres / personnels de l'entreprise : .1", 'Nombre de femmes : .3', "Nombre d'hommes : .3", "Date de création de l'entreprise : .1", "Numéro d'enregistrement / immatriculation : .3", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .3', 'Adresse du siège de l’entreprise: .1', 'Coordonnées GPS : .1', '_Coordonnées GPS : _latitude.1', '_Coordonnées GPS : _longitude.1', '_Coordonnées GPS : _altitude.1', '_Coordonnées GPS : _precision.1', 'Adresse électronique de l’entreprise : .1', 'Statut actuel de l’enquêté (entreprise) dans la famille : .1', "Statut sur le plan foncier (lieu d'installation) ", 'Produits commercialisés à base de plantes à racines et à tubercules  :', 'Produits commercialisés à base de manioc  :', 'Produits commercialisés à base de manioc  :/Gari ', 'Produits commercialisés à base de manioc  :/Tapioca', 'Produits commercialisés à base de manioc  :/Cosette de manioc', 'Produits commercialisés à base de manioc  :/Purée de manioc', 'Produits commercialisés à base de manioc  :/Amidon', 'Produits commercialisés à base de manioc  :/Ethanol de manioc', 'Produits commercialisés à base de manioc  :/Autres ', 'Produits commercialisés à base de manioc  :/Pate fermentée à base de manioc (Agbelima)', 'Autres.2', 'Volume moyen annuel de produits achetés (en tonnes) ', 'Volume moyen annuel de produits vendus  (en tonnes) : ', 'Autres productions que vous commercialisez à part les plantes à racines et à tubercules : ', 'Nom et prénoms du premier responsable.4', 'Sexe du premier responsable : .4', 'Adresse complète du premier responsable : .4', 'Niveau instruction du premier responsable  : .4', 'Numéro de téléphone principal du premier responsable :  .4', 'Numéro de téléphone secondaire du premier responsable :  .4', 'Adresse électronique (mail) du premier responsable : .4', 'Statut sur le plan foncier du premier responsable : .4', "Raison sociale de l'entreprise .2", 'Statut juridique :.2', 'Autres: .2', "Effectif des membres / personnels de l'entreprise : .2", 'Nombre de femmes : .4', "Nombre d'hommes : .4", "Date de création de l'entreprise : .2", "Numéro d'enregistrement / immatriculation : .4", 'Date d’immatriculation (si elle est immatriculée) : ', 'Adresse du siège de l’entreprise: .2', 'Coordonnées GPS : .2', '_Coordonnées GPS : _latitude.2', '_Coordonnées GPS : _longitude.2', '_Coordonnées GPS : _altitude.2', '_Coordonnées GPS : _precision.2', 'Adresse électronique de l’entreprise : .2', 'Statut actuel de l’enquêté (entreprise) dans la famille : .2', "Statut sur le plan foncier (lieu d'installation) .1", 'Produits commercialisés/exportés à base de plantes à racines et tubercules  :', 'Produits commercialisés/exportés à base de manioc  :', 'Produits commercialisés/exportés à base de manioc  :/Gari ', 'Produits commercialisés/exportés à base de manioc  :/Tapioca', 'Produits commercialisés/exportés à base de manioc  :/Cosette de manioc', 'Produits commercialisés/exportés à base de manioc  :/Purée de manioc', 'Produits commercialisés/exportés à base de manioc  :/Amidon', 'Produits commercialisés/exportés à base de manioc  :/Ethanol de manioc', 'Produits commercialisés/exportés à base de manioc  :/Autres ', 'Produits commercialisés/exportés à base de manioc  :/Pate fermentée à base de manioc (Agbelima)', 'Autres.3', 'Volume moyen annuel de produits achetés  (en tonnes) : ', 'Volume moyen annuel de produits vendus  (en tonnes) : .1', 'Type de certification : .1', "Nom de l'organisme certificateur :.1", "Nom de l'organisme certificateur :/CCPB.1", "Nom de l'organisme certificateur :/ECOCERT.1", "Nom de l'organisme certificateur :/SRS.1", "Nom de l'organisme certificateur :/ONECERT.1", "Nom de l'organisme certificateur :/CONTROL.1", "Nom de l'organisme certificateur :/UNION.1", "Nom de l'organisme certificateur :/CERES.1", "Nom de l'organisme certificateur :/Global Gap.2", "Nom de l'organisme certificateur :/Bio SPG.2", "Nom de l'organisme certificateur :/Global Gap.3", "Nom de l'organisme certificateur :/Bio SPG.3", 'Autres productions que vous commercialisez à part les plantes à racines et à tubercules : .1', 'Numéro de téléphone secondaire : .1', 'Numéro de téléphone principal du premier responsable :  .5', 'Numéro de téléphone secondaire du premier responsable :  .5', 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes à racines et à tubercules  ( en ha) :  ', 'Numéro de téléphone principal du premier responsable :  .6', 'Numéro de téléphone secondaire du premier responsable :  .6', "Volume total moyen annuel de Tubercules transformé par l'entreprise (en tonnes) : : ", 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes racines et à tubercules  ( en ha) :  .1', 'Volume total moyen annuel de production de plantes à racines et à tubercules  pour votre organisation ( en tonnes) : .1', 'Autres productions que vous effectuez à part les plantes à tubercules : .1', 'Produits transformés à base de plantes à tubercules  :', 'Volume moyen annuel de vente de tubercules ou dérivés de plantes à tubercules de l’entreprise  (en tonnes) : ', 'Volume moyen annuel de vente de tubercules ou dérivés de plantes à racines et à tubercules de l’entreprise  (en tonnes) : ', 'Volume moyen annuel de vente de tubercules ou dérivés de plantes à racines et à tubercules de l’entreprise  (en tonnes) : .1', 'Produits commercialisés/exportés à base de plantes à tubercules  :', '_id', '_uuid', '_submission_time', '_validation_status', '_notes', '_status', '_submitted_by', '__version__', '_tags', 'meta/rootUuid', '_index']

In [35]:
df = df.drop(columns = ['start', 'end', "Info : Cher(e) participant(e),Dans le cadre de cette enquête, des données personnelles seront collectées. Ces données serviront uniquement à l'actualisation de la base de données des familles membres de l'interprofession. Votre participation est volontaire et vous pouvez arrêter l’entretien à tout moment, sans aucune conséquence négative. Elles ne seront pas transmises à des tiers non impliqués dans l'activité. ", 'Consentez-vous à la collecte et à l’utilisation de vos données comme décrit ci-dessus ?','Type de spéculation : /Manioc', 'Type de spéculation : /Igname', 'Type de spéculation : /Patate douce', 'Type de spéculation : /Souchet','Produits commercialisés à base de manioc  :/Gari ', 'Produits commercialisés à base de manioc  :/Tapioca', 'Produits commercialisés à base de manioc  :/Cosette de manioc', 'Produits commercialisés à base de manioc  :/Purée de manioc', 'Produits commercialisés à base de manioc  :/Amidon', 'Produits commercialisés à base de manioc  :/Ethanol de manioc', 'Produits commercialisés à base de manioc  :/Autres ', 'Produits commercialisés à base de manioc  :/Pate fermentée à base de manioc (Agbelima)','Produits transformés à base de manioc  :', 'Produits transformés à base de manioc  :/Gari ', 'Produits transformés à base de manioc  :/Tapioca', 'Produits transformés à base de manioc  :/Cosette de manioc', 'Produits transformés à base de manioc  :/Purée de manioc', 'Produits transformés à base de manioc  :/Amidon', 'Produits transformés à base de manioc  :/Ethanol de manioc', 'Produits transformés à base de manioc  :/Autres ', 'Produits transformés à base de manioc  :/Pate fermentée à base de manioc (Agbelima)','_id', '_uuid', '_submission_time', '_validation_status', '_notes', '_status', '_submitted_by', '__version__', '_tags', 'meta/rootUuid', '_index'])

In [36]:
print(df.columns.tolist())

['Date de l’enquête : ', 'Nom et prénoms de l’enquêteur : ', "Village de l'enquête : ", "Canton de l'enquête : ", "Région de l'enquête : ", "Type d'acteurs: ", 'Type de spéculation : ', 'Nom et prénoms du répondant ', 'Sexe du répondant  : ', 'Niveau instruction du répondant : ', 'Numéro de téléphone principal: ', 'Numéro de téléphone secondaire : ', 'Adresse électronique (mail): ', 'Poste occupé par le répondant  : ', 'Nom et prénoms du premier responsable', 'Sexe du premier responsable : ', 'Adresse complète du premier responsable : ', 'Niveau instruction du premier responsable  : ', 'Numéro de téléphone principal du premier responsable :  ', 'Numéro de téléphone secondaire du premier responsable :  ', 'Adresse électronique (mail) du premier responsable : ', 'Statut sur le plan foncier du premier responsable : ', "Nom de l'organisation de base / structure ", 'Type d’organisation / structure', 'Autres', 'Effectif des membres : ', 'Nombre de femmes : ', "Nombre d'hommes : ", "Date de création de l'organisation : ", "Numéro d'enregistrement / immatriculation : ", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : ', 'Adresse du siège de l’organisation : ', 'Coordonnées GPS du siège ou du premier responsable: ', '_Coordonnées GPS du siège ou du premier responsable: _latitude', '_Coordonnées GPS du siège ou du premier responsable: _longitude', '_Coordonnées GPS du siège ou du premier responsable: _altitude', '_Coordonnées GPS du siège ou du premier responsable: _precision', 'Adresse électronique de l’organisation à la base : ', 'Statut actuel de l’enquêté (organisation à la base) dans la famille : ', 'Nom de l’organisation communale / cantonale : ', 'Nom de l’organisation préfectorale :', "Nom de l'Union membre de la famille : ", 'Superficie totale moyenne emblavée annuellement par votre organisation pour la production de plantes à racines et à tubercules  ( en ha) :  ', 'Volume total moyen annuel de production de souchets pour votre organisation (en tonnes) : ', 'Volume total moyen annuel de production de manioc pour votre organisation ( nombre de boutures)) : ', 'Volume total moyen annuel de production de patates douces pour votre organisation ( nombre de lianes) : ', "Volume total moyen annuel de production d'ignames pour votre organisation ( nombre de semenceaux)) : ", 'Autres productions que vous effectuez à part les plantes à racines et à tubercules : ', 'Nom et prénoms du premier responsable.1', 'Sexe du premier responsable : .1', 'Adresse complète du premier responsable : .1', 'Niveau instruction du premier responsable  : .1', 'Numéro de téléphone principal du premier responsable :  .1', 'Numéro de téléphone secondaire du premier responsable :  .1', 'Adresse électronique (mail) du premier responsable : .1', 'Statut sur le plan foncier du premier responsable : .1', "Nom de l'organisation de base / structure .1", 'Type d’organisation / structure.1', 'Autres.1', 'Effectif des membres : .1', 'Nombre de femmes : .1', "Nombre d'hommes : .1", "Date de création de l'organisation : .1", "Numéro d'enregistrement / immatriculation : .1", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .1', 'Adresse du siège de l’organisation : .1', 'Coordonnées GPS du siège ou du premier responsable: .1', '_Coordonnées GPS du siège ou du premier responsable: _latitude.1', '_Coordonnées GPS du siège ou du premier responsable: _longitude.1', '_Coordonnées GPS du siège ou du premier responsable: _altitude.1', '_Coordonnées GPS du siège ou du premier responsable: _precision.1', 'Adresse électronique de l’organisation à la base : .1', 'Statut actuel de l’enquêté (organisation à la base) dans la famille : .1', 'Nom de l’organisation communale / cantonale : .1', 'Nom de l’organisation préfectorale :.1', "Nom de l'Union membre de la famille : .1", 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes racines et à tubercules  ( en ha) :  ', 'Volume total moyen annuel de production de plantes à racines et à tubercules  pour votre organisation ( en tonnes) : ', 'Autres productions que vous effectuez à part les plantes à racines et à tubercules : .1', 'Nom et prénoms du premier responsable.2', 'Sexe du premier responsable : .2', 'Adresse complète du premier responsable : .2', 'Niveau instruction du premier responsable  : .2', 'Numéro de téléphone principal du premier responsable :  .2', 'Numéro de téléphone secondaire du premier responsable :  .2', 'Adresse électronique (mail) du premier responsable : .2', 'Statut sur le plan foncier du premier responsable : .2', "Raison sociale de l'entreprise ", 'Statut juridique :', 'Autres: ', "Effectif des membres / personnels de l'entreprise : ", 'Nombre de femmes : .2', "Nombre d'hommes : .2", "Date de création de l'entreprise : ", "Numéro d'enregistrement / immatriculation : .2", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .2', 'Adresse du siège de l’entreprise: ', 'Coordonnées GPS : ', '_Coordonnées GPS : _latitude', '_Coordonnées GPS : _longitude', '_Coordonnées GPS : _altitude', '_Coordonnées GPS : _precision', 'Adresse électronique de l’entreprise : ', 'Statut actuel de l’enquêté (entreprise) dans la famille : ', "Statut sur le plan foncier (lieu d'installation de l'unité) ", 'Produits transformés à base de plantes à racines et tubercules  :', 'Autres ', "Volume total moyen annuel de produits transformé par l'entreprise (en tonnes) : ", "Volume moyen annuel de produits vendus  par l'entreprise (en tonnes) : ", 'Type de certification : ', "Nom de l'organisme certificateur :", "Nom de l'organisme certificateur :/CCPB", "Nom de l'organisme certificateur :/ECOCERT", "Nom de l'organisme certificateur :/SRS", "Nom de l'organisme certificateur :/ONECERT", "Nom de l'organisme certificateur :/CONTROL", "Nom de l'organisme certificateur :/UNION", "Nom de l'organisme certificateur :/CERES", "Nom de l'organisme certificateur :/Global Gap", "Nom de l'organisme certificateur :/Bio SPG", "Nom de l'organisme certificateur :/Global Gap.1", "Nom de l'organisme certificateur :/Bio SPG.1", 'Autres productions que vous effectuez à part les plantes à tubercules : ', 'Nom et prénoms du premier responsable.3', 'Sexe du premier responsable : .3', 'Adresse complète du premier responsable : .3', 'Niveau instruction du premier responsable  : .3', 'Numéro de téléphone principal du premier responsable :  .3', 'Numéro de téléphone secondaire du premier responsable :  .3', 'Adresse électronique (mail) du premier responsable : .3', 'Statut sur le plan foncier du premier responsable : .3', "Raison sociale de l'entreprise .1", 'Statut juridique :.1', 'Autres: .1', "Effectif des membres / personnels de l'entreprise : .1", 'Nombre de femmes : .3', "Nombre d'hommes : .3", "Date de création de l'entreprise : .1", "Numéro d'enregistrement / immatriculation : .3", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .3', 'Adresse du siège de l’entreprise: .1', 'Coordonnées GPS : .1', '_Coordonnées GPS : _latitude.1', '_Coordonnées GPS : _longitude.1', '_Coordonnées GPS : _altitude.1', '_Coordonnées GPS : _precision.1', 'Adresse électronique de l’entreprise : .1', 'Statut actuel de l’enquêté (entreprise) dans la famille : .1', "Statut sur le plan foncier (lieu d'installation) ", 'Produits commercialisés à base de plantes à racines et à tubercules  :', 'Produits commercialisés à base de manioc  :', 'Autres.2', 'Volume moyen annuel de produits achetés (en tonnes) ', 'Volume moyen annuel de produits vendus  (en tonnes) : ', 'Autres productions que vous commercialisez à part les plantes à racines et à tubercules : ', 'Nom et prénoms du premier responsable.4', 'Sexe du premier responsable : .4', 'Adresse complète du premier responsable : .4', 'Niveau instruction du premier responsable  : .4', 'Numéro de téléphone principal du premier responsable :  .4', 'Numéro de téléphone secondaire du premier responsable :  .4', 'Adresse électronique (mail) du premier responsable : .4', 'Statut sur le plan foncier du premier responsable : .4', "Raison sociale de l'entreprise .2", 'Statut juridique :.2', 'Autres: .2', "Effectif des membres / personnels de l'entreprise : .2", 'Nombre de femmes : .4', "Nombre d'hommes : .4", "Date de création de l'entreprise : .2", "Numéro d'enregistrement / immatriculation : .4", 'Date d’immatriculation (si elle est immatriculée) : ', 'Adresse du siège de l’entreprise: .2', 'Coordonnées GPS : .2', '_Coordonnées GPS : _latitude.2', '_Coordonnées GPS : _longitude.2', '_Coordonnées GPS : _altitude.2', '_Coordonnées GPS : _precision.2', 'Adresse électronique de l’entreprise : .2', 'Statut actuel de l’enquêté (entreprise) dans la famille : .2', "Statut sur le plan foncier (lieu d'installation) .1", 'Produits commercialisés/exportés à base de plantes à racines et tubercules  :', 'Produits commercialisés/exportés à base de manioc  :', 'Produits commercialisés/exportés à base de manioc  :/Gari ', 'Produits commercialisés/exportés à base de manioc  :/Tapioca', 'Produits commercialisés/exportés à base de manioc  :/Cosette de manioc', 'Produits commercialisés/exportés à base de manioc  :/Purée de manioc', 'Produits commercialisés/exportés à base de manioc  :/Amidon', 'Produits commercialisés/exportés à base de manioc  :/Ethanol de manioc', 'Produits commercialisés/exportés à base de manioc  :/Autres ', 'Produits commercialisés/exportés à base de manioc  :/Pate fermentée à base de manioc (Agbelima)', 'Autres.3', 'Volume moyen annuel de produits achetés  (en tonnes) : ', 'Volume moyen annuel de produits vendus  (en tonnes) : .1', 'Type de certification : .1', "Nom de l'organisme certificateur :.1", "Nom de l'organisme certificateur :/CCPB.1", "Nom de l'organisme certificateur :/ECOCERT.1", "Nom de l'organisme certificateur :/SRS.1", "Nom de l'organisme certificateur :/ONECERT.1", "Nom de l'organisme certificateur :/CONTROL.1", "Nom de l'organisme certificateur :/UNION.1", "Nom de l'organisme certificateur :/CERES.1", "Nom de l'organisme certificateur :/Global Gap.2", "Nom de l'organisme certificateur :/Bio SPG.2", "Nom de l'organisme certificateur :/Global Gap.3", "Nom de l'organisme certificateur :/Bio SPG.3", 'Autres productions que vous commercialisez à part les plantes à racines et à tubercules : .1', 'Numéro de téléphone secondaire : .1', 'Numéro de téléphone principal du premier responsable :  .5', 'Numéro de téléphone secondaire du premier responsable :  .5', 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes à racines et à tubercules  ( en ha) :  ', 'Numéro de téléphone principal du premier responsable :  .6', 'Numéro de téléphone secondaire du premier responsable :  .6', "Volume total moyen annuel de Tubercules transformé par l'entreprise (en tonnes) : : ", 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes racines et à tubercules  ( en ha) :  .1', 'Volume total moyen annuel de production de plantes à racines et à tubercules  pour votre organisation ( en tonnes) : .1', 'Autres productions que vous effectuez à part les plantes à tubercules : .1', 'Produits transformés à base de plantes à tubercules  :', 'Volume moyen annuel de vente de tubercules ou dérivés de plantes à tubercules de l’entreprise  (en tonnes) : ', 'Volume moyen annuel de vente de tubercules ou dérivés de plantes à racines et à tubercules de l’entreprise  (en tonnes) : ', 'Volume moyen annuel de vente de tubercules ou dérivés de plantes à racines et à tubercules de l’entreprise  (en tonnes) : .1', 'Produits commercialisés/exportés à base de plantes à tubercules  :']

In [37]:
df = df.drop(columns = ['Produits commercialisés/exportés à base de manioc  :', 'Produits commercialisés/exportés à base de manioc  :/Gari ', 'Produits commercialisés/exportés à base de manioc  :/Tapioca', 'Produits commercialisés/exportés à base de manioc  :/Cosette de manioc', 'Produits commercialisés/exportés à base de manioc  :/Purée de manioc', 'Produits commercialisés/exportés à base de manioc  :/Amidon', 'Produits commercialisés/exportés à base de manioc  :/Ethanol de manioc', 'Produits commercialisés/exportés à base de manioc  :/Autres ', 'Produits commercialisés/exportés à base de manioc  :/Pate fermentée à base de manioc (Agbelima)',"Nom de l'organisme certificateur :/CCPB", "Nom de l'organisme certificateur :/ECOCERT", "Nom de l'organisme certificateur :/SRS", "Nom de l'organisme certificateur :/ONECERT", "Nom de l'organisme certificateur :/CONTROL", "Nom de l'organisme certificateur :/UNION", "Nom de l'organisme certificateur :/CERES", "Nom de l'organisme certificateur :/Global Gap", "Nom de l'organisme certificateur :/Bio SPG", "Nom de l'organisme certificateur :/Global Gap.1", "Nom de l'organisme certificateur :/Bio SPG.1","Nom de l'organisme certificateur :.1", "Nom de l'organisme certificateur :/CCPB.1", "Nom de l'organisme certificateur :/ECOCERT.1", "Nom de l'organisme certificateur :/SRS.1", "Nom de l'organisme certificateur :/ONECERT.1", "Nom de l'organisme certificateur :/CONTROL.1", "Nom de l'organisme certificateur :/UNION.1", "Nom de l'organisme certificateur :/CERES.1", "Nom de l'organisme certificateur :/Global Gap.2", "Nom de l'organisme certificateur :/Bio SPG.2", "Nom de l'organisme certificateur :/Global Gap.3", "Nom de l'organisme certificateur :/Bio SPG.3"])

In [38]:
print(df.columns.tolist())

['Date de l’enquête : ', 'Nom et prénoms de l’enquêteur : ', "Village de l'enquête : ", "Canton de l'enquête : ", "Région de l'enquête : ", "Type d'acteurs: ", 'Type de spéculation : ', 'Nom et prénoms du répondant ', 'Sexe du répondant  : ', 'Niveau instruction du répondant : ', 'Numéro de téléphone principal: ', 'Numéro de téléphone secondaire : ', 'Adresse électronique (mail): ', 'Poste occupé par le répondant  : ', 'Nom et prénoms du premier responsable', 'Sexe du premier responsable : ', 'Adresse complète du premier responsable : ', 'Niveau instruction du premier responsable  : ', 'Numéro de téléphone principal du premier responsable :  ', 'Numéro de téléphone secondaire du premier responsable :  ', 'Adresse électronique (mail) du premier responsable : ', 'Statut sur le plan foncier du premier responsable : ', "Nom de l'organisation de base / structure ", 'Type d’organisation / structure', 'Autres', 'Effectif des membres : ', 'Nombre de femmes : ', "Nombre d'hommes : ", "Date de création de l'organisation : ", "Numéro d'enregistrement / immatriculation : ", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : ', 'Adresse du siège de l’organisation : ', 'Coordonnées GPS du siège ou du premier responsable: ', '_Coordonnées GPS du siège ou du premier responsable: _latitude', '_Coordonnées GPS du siège ou du premier responsable: _longitude', '_Coordonnées GPS du siège ou du premier responsable: _altitude', '_Coordonnées GPS du siège ou du premier responsable: _precision', 'Adresse électronique de l’organisation à la base : ', 'Statut actuel de l’enquêté (organisation à la base) dans la famille : ', 'Nom de l’organisation communale / cantonale : ', 'Nom de l’organisation préfectorale :', "Nom de l'Union membre de la famille : ", 'Superficie totale moyenne emblavée annuellement par votre organisation pour la production de plantes à racines et à tubercules  ( en ha) :  ', 'Volume total moyen annuel de production de souchets pour votre organisation (en tonnes) : ', 'Volume total moyen annuel de production de manioc pour votre organisation ( nombre de boutures)) : ', 'Volume total moyen annuel de production de patates douces pour votre organisation ( nombre de lianes) : ', "Volume total moyen annuel de production d'ignames pour votre organisation ( nombre de semenceaux)) : ", 'Autres productions que vous effectuez à part les plantes à racines et à tubercules : ', 'Nom et prénoms du premier responsable.1', 'Sexe du premier responsable : .1', 'Adresse complète du premier responsable : .1', 'Niveau instruction du premier responsable  : .1', 'Numéro de téléphone principal du premier responsable :  .1', 'Numéro de téléphone secondaire du premier responsable :  .1', 'Adresse électronique (mail) du premier responsable : .1', 'Statut sur le plan foncier du premier responsable : .1', "Nom de l'organisation de base / structure .1", 'Type d’organisation / structure.1', 'Autres.1', 'Effectif des membres : .1', 'Nombre de femmes : .1', "Nombre d'hommes : .1", "Date de création de l'organisation : .1", "Numéro d'enregistrement / immatriculation : .1", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .1', 'Adresse du siège de l’organisation : .1', 'Coordonnées GPS du siège ou du premier responsable: .1', '_Coordonnées GPS du siège ou du premier responsable: _latitude.1', '_Coordonnées GPS du siège ou du premier responsable: _longitude.1', '_Coordonnées GPS du siège ou du premier responsable: _altitude.1', '_Coordonnées GPS du siège ou du premier responsable: _precision.1', 'Adresse électronique de l’organisation à la base : .1', 'Statut actuel de l’enquêté (organisation à la base) dans la famille : .1', 'Nom de l’organisation communale / cantonale : .1', 'Nom de l’organisation préfectorale :.1', "Nom de l'Union membre de la famille : .1", 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes racines et à tubercules  ( en ha) :  ', 'Volume total moyen annuel de production de plantes à racines et à tubercules  pour votre organisation ( en tonnes) : ', 'Autres productions que vous effectuez à part les plantes à racines et à tubercules : .1', 'Nom et prénoms du premier responsable.2', 'Sexe du premier responsable : .2', 'Adresse complète du premier responsable : .2', 'Niveau instruction du premier responsable  : .2', 'Numéro de téléphone principal du premier responsable :  .2', 'Numéro de téléphone secondaire du premier responsable :  .2', 'Adresse électronique (mail) du premier responsable : .2', 'Statut sur le plan foncier du premier responsable : .2', "Raison sociale de l'entreprise ", 'Statut juridique :', 'Autres: ', "Effectif des membres / personnels de l'entreprise : ", 'Nombre de femmes : .2', "Nombre d'hommes : .2", "Date de création de l'entreprise : ", "Numéro d'enregistrement / immatriculation : .2", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .2', 'Adresse du siège de l’entreprise: ', 'Coordonnées GPS : ', '_Coordonnées GPS : _latitude', '_Coordonnées GPS : _longitude', '_Coordonnées GPS : _altitude', '_Coordonnées GPS : _precision', 'Adresse électronique de l’entreprise : ', 'Statut actuel de l’enquêté (entreprise) dans la famille : ', "Statut sur le plan foncier (lieu d'installation de l'unité) ", 'Produits transformés à base de plantes à racines et tubercules  :', 'Autres ', "Volume total moyen annuel de produits transformé par l'entreprise (en tonnes) : ", "Volume moyen annuel de produits vendus  par l'entreprise (en tonnes) : ", 'Type de certification : ', "Nom de l'organisme certificateur :", 'Autres productions que vous effectuez à part les plantes à tubercules : ', 'Nom et prénoms du premier responsable.3', 'Sexe du premier responsable : .3', 'Adresse complète du premier responsable : .3', 'Niveau instruction du premier responsable  : .3', 'Numéro de téléphone principal du premier responsable :  .3', 'Numéro de téléphone secondaire du premier responsable :  .3', 'Adresse électronique (mail) du premier responsable : .3', 'Statut sur le plan foncier du premier responsable : .3', "Raison sociale de l'entreprise .1", 'Statut juridique :.1', 'Autres: .1', "Effectif des membres / personnels de l'entreprise : .1", 'Nombre de femmes : .3', "Nombre d'hommes : .3", "Date de création de l'entreprise : .1", "Numéro d'enregistrement / immatriculation : .3", 'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .3', 'Adresse du siège de l’entreprise: .1', 'Coordonnées GPS : .1', '_Coordonnées GPS : _latitude.1', '_Coordonnées GPS : _longitude.1', '_Coordonnées GPS : _altitude.1', '_Coordonnées GPS : _precision.1', 'Adresse électronique de l’entreprise : .1', 'Statut actuel de l’enquêté (entreprise) dans la famille : .1', "Statut sur le plan foncier (lieu d'installation) ", 'Produits commercialisés à base de plantes à racines et à tubercules  :', 'Produits commercialisés à base de manioc  :', 'Autres.2', 'Volume moyen annuel de produits achetés (en tonnes) ', 'Volume moyen annuel de produits vendus  (en tonnes) : ', 'Autres productions que vous commercialisez à part les plantes à racines et à tubercules : ', 'Nom et prénoms du premier responsable.4', 'Sexe du premier responsable : .4', 'Adresse complète du premier responsable : .4', 'Niveau instruction du premier responsable  : .4', 'Numéro de téléphone principal du premier responsable :  .4', 'Numéro de téléphone secondaire du premier responsable :  .4', 'Adresse électronique (mail) du premier responsable : .4', 'Statut sur le plan foncier du premier responsable : .4', "Raison sociale de l'entreprise .2", 'Statut juridique :.2', 'Autres: .2', "Effectif des membres / personnels de l'entreprise : .2", 'Nombre de femmes : .4', "Nombre d'hommes : .4", "Date de création de l'entreprise : .2", "Numéro d'enregistrement / immatriculation : .4", 'Date d’immatriculation (si elle est immatriculée) : ', 'Adresse du siège de l’entreprise: .2', 'Coordonnées GPS : .2', '_Coordonnées GPS : _latitude.2', '_Coordonnées GPS : _longitude.2', '_Coordonnées GPS : _altitude.2', '_Coordonnées GPS : _precision.2', 'Adresse électronique de l’entreprise : .2', 'Statut actuel de l’enquêté (entreprise) dans la famille : .2', "Statut sur le plan foncier (lieu d'installation) .1", 'Produits commercialisés/exportés à base de plantes à racines et tubercules  :', 'Autres.3', 'Volume moyen annuel de produits achetés  (en tonnes) : ', 'Volume moyen annuel de produits vendus  (en tonnes) : .1', 'Type de certification : .1', 'Autres productions que vous commercialisez à part les plantes à racines et à tubercules : .1', 'Numéro de téléphone secondaire : .1', 'Numéro de téléphone principal du premier responsable :  .5', 'Numéro de téléphone secondaire du premier responsable :  .5', 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes à racines et à tubercules  ( en ha) :  ', 'Numéro de téléphone principal du premier responsable :  .6', 'Numéro de téléphone secondaire du premier responsable :  .6', "Volume total moyen annuel de Tubercules transformé par l'entreprise (en tonnes) : : ", 'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes racines et à tubercules  ( en ha) :  .1', 'Volume total moyen annuel de production de plantes à racines et à tubercules  pour votre organisation ( en tonnes) : .1', 'Autres productions que vous effectuez à part les plantes à tubercules : .1', 'Produits transformés à base de plantes à tubercules  :', 'Volume moyen annuel de vente de tubercules ou dérivés de plantes à tubercules de l’entreprise  (en tonnes) : ', 'Volume moyen annuel de vente de tubercules ou dérivés de plantes à racines et à tubercules de l’entreprise  (en tonnes) : ', 'Volume moyen annuel de vente de tubercules ou dérivés de plantes à racines et à tubercules de l’entreprise  (en tonnes) : .1', 'Produits commercialisés/exportés à base de plantes à tubercules  :']

In [39]:
dictionnaire_renommage_prt = {
    # 1. INFORMATIONS GÉNÉRALES ET RÉPONDANT
    'Date de l’enquête : ': 'date_enquete',
    'Nom et prénoms de l’enquêteur : ': 'nom_enqueteur',
    "Village de l'enquête : ": 'village',
    "Canton de l'enquête : ": 'canton',
    "Région de l'enquête : ": 'region',
    "Type d'acteurs: ": 'type_acteur',
    'Type de spéculation : ': 'type_speculation',
    'Nom et prénoms du répondant ': 'nom_repondant',
    'Sexe du répondant  : ': 'sexe_repondant',
    'Niveau instruction du répondant : ': 'instruction_repondant',
    'Numéro de téléphone principal: ': 'tel_principal_repondant',
    'Numéro de téléphone secondaire : ': 'tel_secondaire_repondant',
    'Adresse électronique (mail): ': 'email_repondant',
    'Poste occupé par le répondant  : ': 'poste_repondant',

    # 2. GROUPE 1 (Sans suffixe)
    'Nom et prénoms du premier responsable': 'nom_resp_1',
    'Sexe du premier responsable : ': 'sexe_resp_1',
    'Adresse complète du premier responsable : ': 'adresse_resp_1',
    'Niveau instruction du premier responsable  : ': 'instruction_resp_1',
    'Numéro de téléphone principal du premier responsable :  ': 'tel1_resp_1',
    'Numéro de téléphone secondaire du premier responsable :  ': 'tel2_resp_1',
    'Adresse électronique (mail) du premier responsable : ': 'email_resp_1',
    'Statut sur le plan foncier du premier responsable : ': 'statut_foncier_resp_1',
    "Nom de l'organisation de base / structure ": 'nom_structure_1',
    'Type d’organisation / structure': 'type_structure_1',
    'Autres': 'autres_structure_1',
    'Effectif des membres : ': 'effectif_1',
    'Nombre de femmes : ': 'nb_femmes_1',
    "Nombre d'hommes : ": 'nb_hommes_1',
    "Date de création de l'organisation : ": 'date_creation_1',
    "Numéro d'enregistrement / immatriculation : ": 'num_immatriculation_1',
    'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : ': 'date_immatriculation_1',
    'Adresse du siège de l’organisation : ': 'adresse_siege_1',
    'Coordonnées GPS du siège ou du premier responsable: ': 'gps_1',
    '_Coordonnées GPS du siège ou du premier responsable: _latitude': 'gps_lat_1',
    '_Coordonnées GPS du siège ou du premier responsable: _longitude': 'gps_lon_1',
    '_Coordonnées GPS du siège ou du premier responsable: _altitude': 'gps_alt_1',
    '_Coordonnées GPS du siège ou du premier responsable: _precision': 'gps_prec_1',
    'Adresse électronique de l’organisation à la base : ': 'email_orga_1',
    'Statut actuel de l’enquêté (organisation à la base) dans la famille : ': 'statut_famille_1',
    'Nom de l’organisation communale / cantonale : ': 'orga_communale_1',
    'Nom de l’organisation préfectorale :': 'orga_prefectorale_1',
    "Nom de l'Union membre de la famille : ": 'union_membre_1',
    'Superficie totale moyenne emblavée annuellement par votre organisation pour la production de plantes à racines et à tubercules  ( en ha) :  ': 'superficie_prt_1',
    'Volume total moyen annuel de production de souchets pour votre organisation (en tonnes) : ': 'vol_prod_souchet_1',
    'Volume total moyen annuel de production de manioc pour votre organisation ( nombre de boutures)) : ': 'vol_prod_manioc_1',
    'Volume total moyen annuel de production de patates douces pour votre organisation ( nombre de lianes) : ': 'vol_prod_patates_1',
    "Volume total moyen annuel de production d'ignames pour votre organisation ( nombre de semenceaux)) : ": 'vol_prod_ignames_1',
    'Autres productions que vous effectuez à part les plantes à racines et à tubercules : ': 'autres_productions_1',

    # 3. GROUPE 2 (Suffixe .1 pour les responsables)
    'Nom et prénoms du premier responsable.1': 'nom_resp_2',
    'Sexe du premier responsable : .1': 'sexe_resp_2',
    'Adresse complète du premier responsable : .1': 'adresse_resp_2',
    'Niveau instruction du premier responsable  : .1': 'instruction_resp_2',
    'Numéro de téléphone principal du premier responsable :  .1': 'tel1_resp_2',
    'Numéro de téléphone secondaire du premier responsable :  .1': 'tel2_resp_2',
    'Adresse électronique (mail) du premier responsable : .1': 'email_resp_2',
    'Statut sur le plan foncier du premier responsable : .1': 'statut_foncier_resp_2',
    "Nom de l'organisation de base / structure .1": 'nom_structure_2',
    'Type d’organisation / structure.1': 'type_structure_2',
    'Autres.1': 'autres_structure_2',
    'Effectif des membres : .1': 'effectif_2',
    'Nombre de femmes : .1': 'nb_femmes_2',
    "Nombre d'hommes : .1": 'nb_hommes_2',
    "Date de création de l'organisation : .1": 'date_creation_2',
    "Numéro d'enregistrement / immatriculation : .1": 'num_immatriculation_2',
    'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .1': 'date_immatriculation_2',
    'Adresse du siège de l’organisation : .1': 'adresse_siege_2',
    'Coordonnées GPS du siège ou du premier responsable: .1': 'gps_2',
    '_Coordonnées GPS du siège ou du premier responsable: _latitude.1': 'gps_lat_2',
    '_Coordonnées GPS du siège ou du premier responsable: _longitude.1': 'gps_lon_2',
    '_Coordonnées GPS du siège ou du premier responsable: _altitude.1': 'gps_alt_2',
    '_Coordonnées GPS du siège ou du premier responsable: _precision.1': 'gps_prec_2',
    'Adresse électronique de l’organisation à la base : .1': 'email_orga_2',
    'Statut actuel de l’enquêté (organisation à la base) dans la famille : .1': 'statut_famille_2',
    'Nom de l’organisation communale / cantonale : .1': 'orga_communale_2',
    'Nom de l’organisation préfectorale :.1': 'orga_prefectorale_2',
    "Nom de l'Union membre de la famille : .1": 'union_membre_2',
    'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes racines et à tubercules  ( en ha) :  ': 'superficie_prt_2',
    'Volume total moyen annuel de production de plantes à racines et à tubercules  pour votre organisation ( en tonnes) : ': 'vol_prod_prt_2',
    'Autres productions que vous effectuez à part les plantes à racines et à tubercules : .1': 'autres_productions_2',

    # 4. GROUPE 3 (Suffixe .2 pour les responsables - Transformateurs)
    'Nom et prénoms du premier responsable.2': 'nom_resp_3',
    'Sexe du premier responsable : .2': 'sexe_resp_3',
    'Adresse complète du premier responsable : .2': 'adresse_resp_3',
    'Niveau instruction du premier responsable  : .2': 'instruction_resp_3',
    'Numéro de téléphone principal du premier responsable :  .2': 'tel1_resp_3',
    'Numéro de téléphone secondaire du premier responsable :  .2': 'tel2_resp_3',
    'Adresse électronique (mail) du premier responsable : .2': 'email_resp_3',
    'Statut sur le plan foncier du premier responsable : .2': 'statut_foncier_resp_3',
    "Raison sociale de l'entreprise ": 'nom_structure_3',
    'Statut juridique :': 'statut_juridique_3',
    'Autres: ': 'autres_structure_3',
    "Effectif des membres / personnels de l'entreprise : ": 'effectif_3',
    'Nombre de femmes : .2': 'nb_femmes_3',
    "Nombre d'hommes : .2": 'nb_hommes_3',
    "Date de création de l'entreprise : ": 'date_creation_3',
    "Numéro d'enregistrement / immatriculation : .2": 'num_immatriculation_3',
    'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .2': 'date_immatriculation_3',
    'Adresse du siège de l’entreprise: ': 'adresse_siege_3',
    'Coordonnées GPS : ': 'gps_3',
    '_Coordonnées GPS : _latitude': 'gps_lat_3',
    '_Coordonnées GPS : _longitude': 'gps_lon_3',
    '_Coordonnées GPS : _altitude': 'gps_alt_3',
    '_Coordonnées GPS : _precision': 'gps_prec_3',
    'Adresse électronique de l’entreprise : ': 'email_entreprise_3',
    'Statut actuel de l’enquêté (entreprise) dans la famille : ': 'statut_famille_3',
    "Statut sur le plan foncier (lieu d'installation de l'unité) ": 'statut_foncier_unite_3',
    'Produits transformés à base de plantes à racines et tubercules  :': 'prod_transformes_3',
    'Autres ': 'autres_derives_3',
    "Volume total moyen annuel de produits transformé par l'entreprise (en tonnes) : ": 'vol_transforme_3',
    "Volume moyen annuel de produits vendus  par l'entreprise (en tonnes) : ": 'vol_vendu_3',
    'Type de certification : ': 'type_certif_3',
    "Nom de l'organisme certificateur :": 'nom_certif_3',
    'Autres productions que vous effectuez à part les plantes à tubercules : ': 'autres_productions_3',

    # 5. GROUPE 4 (Suffixe .3 pour les responsables - Commerçants)
    'Nom et prénoms du premier responsable.3': 'nom_resp_4',
    'Sexe du premier responsable : .3': 'sexe_resp_4',
    'Adresse complète du premier responsable : .3': 'adresse_resp_4',
    'Niveau instruction du premier responsable  : .3': 'instruction_resp_4',
    'Numéro de téléphone principal du premier responsable :  .3': 'tel1_resp_4',
    'Numéro de téléphone secondaire du premier responsable :  .3': 'tel2_resp_4',
    'Adresse électronique (mail) du premier responsable : .3': 'email_resp_4',
    'Statut sur le plan foncier du premier responsable : .3': 'statut_foncier_resp_4',
    "Raison sociale de l'entreprise .1": 'nom_structure_4',
    'Statut juridique :.1': 'statut_juridique_4',
    'Autres: .1': 'autres_structure_4',
    "Effectif des membres / personnels de l'entreprise : .1": 'effectif_4',
    'Nombre de femmes : .3': 'nb_femmes_4',
    "Nombre d'hommes : .3": 'nb_hommes_4',
    "Date de création de l'entreprise : .1": 'date_creation_4',
    "Numéro d'enregistrement / immatriculation : .3": 'num_immatriculation_4',
    'Date d’immatriculation de l’organisation à la base (si elle est immatriculée) : .3': 'date_immatriculation_4',
    'Adresse du siège de l’entreprise: .1': 'adresse_siege_4',
    'Coordonnées GPS : .1': 'gps_4',
    '_Coordonnées GPS : _latitude.1': 'gps_lat_4',
    '_Coordonnées GPS : _longitude.1': 'gps_lon_4',
    '_Coordonnées GPS : _altitude.1': 'gps_alt_4',
    '_Coordonnées GPS : _precision.1': 'gps_prec_4',
    'Adresse électronique de l’entreprise : .1': 'email_entreprise_4',
    'Statut actuel de l’enquêté (entreprise) dans la famille : .1': 'statut_famille_4',
    "Statut sur le plan foncier (lieu d'installation) ": 'statut_foncier_unite_4',
    'Produits commercialisés à base de plantes à racines et à tubercules  :': 'prod_commercialises_4',
    'Produits commercialisés à base de manioc  :': 'prod_commercialises_manioc_4',
    'Autres.2': 'autres_derives_4',
    'Volume moyen annuel de produits achetés (en tonnes) ': 'vol_achete_4',
    'Volume moyen annuel de produits vendus  (en tonnes) : ': 'vol_vendu_4',
    'Autres productions que vous commercialisez à part les plantes à racines et à tubercules : ': 'autres_productions_4',

    # 6. GROUPE 5 (Suffixe .4 pour les responsables - Exportateurs/Autres)
    'Nom et prénoms du premier responsable.4': 'nom_resp_5',
    'Sexe du premier responsable : .4': 'sexe_resp_5',
    'Adresse complète du premier responsable : .4': 'adresse_resp_5',
    'Niveau instruction du premier responsable  : .4': 'instruction_resp_5',
    'Numéro de téléphone principal du premier responsable :  .4': 'tel1_resp_5',
    'Numéro de téléphone secondaire du premier responsable :  .4': 'tel2_resp_5',
    'Adresse électronique (mail) du premier responsable : .4': 'email_resp_5',
    'Statut sur le plan foncier du premier responsable : .4': 'statut_foncier_resp_5',
    "Raison sociale de l'entreprise .2": 'nom_structure_5',
    'Statut juridique :.2': 'statut_juridique_5',
    'Autres: .2': 'autres_structure_5',
    "Effectif des membres / personnels de l'entreprise : .2": 'effectif_5',
    'Nombre de femmes : .4': 'nb_femmes_5',
    "Nombre d'hommes : .4": 'nb_hommes_5',
    "Date de création de l'entreprise : .2": 'date_creation_5',
    "Numéro d'enregistrement / immatriculation : .4": 'num_immatriculation_5',
    'Date d’immatriculation (si elle est immatriculée) : ': 'date_immatriculation_5',
    'Adresse du siège de l’entreprise: .2': 'adresse_siege_5',
    'Coordonnées GPS : .2': 'gps_5',
    '_Coordonnées GPS : _latitude.2': 'gps_lat_5',
    '_Coordonnées GPS : _longitude.2': 'gps_lon_5',
    '_Coordonnées GPS : _altitude.2': 'gps_alt_5',
    '_Coordonnées GPS : _precision.2': 'gps_prec_5',
    'Adresse électronique de l’entreprise : .2': 'email_entreprise_5',
    'Statut actuel de l’enquêté (entreprise) dans la famille : .2': 'statut_famille_5',
    "Statut sur le plan foncier (lieu d'installation) .1": 'statut_foncier_unite_5',
    'Produits commercialisés/exportés à base de plantes à racines et tubercules  :': 'prod_exportes_5',
    'Autres.3': 'autres_derives_5',
    'Volume moyen annuel de produits achetés  (en tonnes) : ': 'vol_achete_5',
    'Volume moyen annuel de produits vendus  (en tonnes) : .1': 'vol_vendu_5',
    'Type de certification : .1': 'type_certif_5',
    'Autres productions que vous commercialisez à part les plantes à racines et à tubercules : .1': 'autres_productions_5',

    # 7. VARIABLES DE FIN / DÉCALÉES
    'Numéro de téléphone secondaire : .1': 'tel_secondaire_autre_1',
    'Numéro de téléphone principal du premier responsable :  .5': 'tel1_resp_6',
    'Numéro de téléphone secondaire du premier responsable :  .5': 'tel2_resp_6',
    'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes à racines et à tubercules  ( en ha) :  ': 'superficie_prt_6',
    'Numéro de téléphone principal du premier responsable :  .6': 'tel1_resp_7',
    'Numéro de téléphone secondaire du premier responsable :  .6': 'tel2_resp_7',
    "Volume total moyen annuel de Tubercules transformé par l'entreprise (en tonnes) : : ": 'vol_transforme_autre_1',
    'Superficie totale moyenne emblavée annuellement par les membres de votre organisation pour la production de plantes racines et à tubercules  ( en ha) :  .1': 'superficie_prt_autre',
    'Volume total moyen annuel de production de plantes à racines et à tubercules  pour votre organisation ( en tonnes) : .1': 'vol_prod_prt_autre',
    'Autres productions que vous effectuez à part les plantes à tubercules : .1': 'autres_productions_autre_1',
    'Produits transformés à base de plantes à tubercules  :': 'prod_transformes_autre',
    'Volume moyen annuel de vente de tubercules ou dérivés de plantes à tubercules de l’entreprise  (en tonnes) : ': 'vol_vente_tubercules_1',
    'Volume moyen annuel de vente de tubercules ou dérivés de plantes à racines et à tubercules de l’entreprise  (en tonnes) : ': 'vol_vente_prt_1',
    'Volume moyen annuel de vente de tubercules ou dérivés de plantes à racines et à tubercules de l’entreprise  (en tonnes) : .1': 'vol_vente_prt_2',
    'Produits commercialisés/exportés à base de plantes à tubercules  :': 'prod_exportes_tubercules'
}

df = df.rename(columns = dictionnaire_renommage_prt)
print(df.columns.tolist())

['date_enquete', 'nom_enqueteur', 'village', 'canton', 'region', 'type_acteur', 'type_speculation', 'nom_repondant', 'sexe_repondant', 'instruction_repondant', 'tel_principal_repondant', 'tel_secondaire_repondant', 'email_repondant', 'poste_repondant', 'nom_resp_1', 'sexe_resp_1', 'adresse_resp_1', 'instruction_resp_1', 'tel1_resp_1', 'tel2_resp_1', 'email_resp_1', 'statut_foncier_resp_1', 'nom_structure_1', 'type_structure_1', 'autres_structure_1', 'effectif_1', 'nb_femmes_1', 'nb_hommes_1', 'date_creation_1', 'num_immatriculation_1', 'date_immatriculation_1', 'adresse_siege_1', 'gps_1', 'gps_lat_1', 'gps_lon_1', 'gps_alt_1', 'gps_prec_1', 'email_orga_1', 'statut_famille_1', 'orga_communale_1', 'orga_prefectorale_1', 'union_membre_1', 'superficie_prt_1', 'vol_prod_souchet_1', 'vol_prod_manioc_1', 'vol_prod_patates_1', 'vol_prod_ignames_1', 'autres_productions_1', 'nom_resp_2', 'sexe_resp_2', 'adresse_resp_2', 'instruction_resp_2', 'tel1_resp_2', 'tel2_resp_2', 'email_resp_2', 'statut_foncier_resp_2', 'nom_structure_2', 'type_structure_2', 'autres_structure_2', 'effectif_2', 'nb_femmes_2', 'nb_hommes_2', 'date_creation_2', 'num_immatriculation_2', 'date_immatriculation_2', 'adresse_siege_2', 'gps_2', 'gps_lat_2', 'gps_lon_2', 'gps_alt_2', 'gps_prec_2', 'email_orga_2', 'statut_famille_2', 'orga_communale_2', 'orga_prefectorale_2', 'union_membre_2', 'superficie_prt_2', 'vol_prod_prt_2', 'autres_productions_2', 'nom_resp_3', 'sexe_resp_3', 'adresse_resp_3', 'instruction_resp_3', 'tel1_resp_3', 'tel2_resp_3', 'email_resp_3', 'statut_foncier_resp_3', 'nom_structure_3', 'statut_juridique_3', 'autres_structure_3', 'effectif_3', 'nb_femmes_3', 'nb_hommes_3', 'date_creation_3', 'num_immatriculation_3', 'date_immatriculation_3', 'adresse_siege_3', 'gps_3', 'gps_lat_3', 'gps_lon_3', 'gps_alt_3', 'gps_prec_3', 'email_entreprise_3', 'statut_famille_3', 'statut_foncier_unite_3', 'prod_transformes_3', 'autres_derives_3', 'vol_transforme_3', 'vol_vendu_3', 'type_certif_3', 'nom_certif_3', 'autres_productions_3', 'nom_resp_4', 'sexe_resp_4', 'adresse_resp_4', 'instruction_resp_4', 'tel1_resp_4', 'tel2_resp_4', 'email_resp_4', 'statut_foncier_resp_4', 'nom_structure_4', 'statut_juridique_4', 'autres_structure_4', 'effectif_4', 'nb_femmes_4', 'nb_hommes_4', 'date_creation_4', 'num_immatriculation_4', 'date_immatriculation_4', 'adresse_siege_4', 'gps_4', 'gps_lat_4', 'gps_lon_4', 'gps_alt_4', 'gps_prec_4', 'email_entreprise_4', 'statut_famille_4', 'statut_foncier_unite_4', 'prod_commercialises_4', 'prod_commercialises_manioc_4', 'autres_derives_4', 'vol_achete_4', 'vol_vendu_4', 'autres_productions_4', 'nom_resp_5', 'sexe_resp_5', 'adresse_resp_5', 'instruction_resp_5', 'tel1_resp_5', 'tel2_resp_5', 'email_resp_5', 'statut_foncier_resp_5', 'nom_structure_5', 'statut_juridique_5', 'autres_structure_5', 'effectif_5', 'nb_femmes_5', 'nb_hommes_5', 'date_creation_5', 'num_immatriculation_5', 'date_immatriculation_5', 'adresse_siege_5', 'gps_5', 'gps_lat_5', 'gps_lon_5', 'gps_alt_5', 'gps_prec_5', 'email_entreprise_5', 'statut_famille_5', 'statut_foncier_unite_5', 'prod_exportes_5', 'autres_derives_5', 'vol_achete_5', 'vol_vendu_5', 'type_certif_5', 'autres_productions_5', 'tel_secondaire_autre_1', 'tel1_resp_6', 'tel2_resp_6', 'superficie_prt_6', 'tel1_resp_7', 'tel2_resp_7', 'vol_transforme_autre_1', 'superficie_prt_autre', 'vol_prod_prt_autre', 'autres_productions_autre_1', 'prod_transformes_autre', 'vol_vente_tubercules_1', 'vol_vente_prt_1', 'vol_vente_prt_2', 'prod_exportes_tubercules']

In [40]:
fusions_a_faire_prt = {
    # 1. IDENTITÉ DU RESPONSABLE 
    'nom_resp_final': ['nom_resp_1', 'nom_resp_2', 'nom_resp_3', 'nom_resp_4', 'nom_resp_5'],
    'sexe_resp_final': ['sexe_resp_1', 'sexe_resp_2', 'sexe_resp_3', 'sexe_resp_4', 'sexe_resp_5'],
    'adresse_resp_final': ['adresse_resp_1', 'adresse_resp_2', 'adresse_resp_3', 'adresse_resp_4', 'adresse_resp_5'],
    'instruction_resp_final': ['instruction_resp_1', 'instruction_resp_2', 'instruction_resp_3', 'instruction_resp_4', 'instruction_resp_5'],
    'email_resp_final': ['email_resp_1', 'email_resp_2', 'email_resp_3', 'email_resp_4', 'email_resp_5'],
    'tel_principal_resp_final': ['tel1_resp_1', 'tel1_resp_2', 'tel1_resp_3', 'tel1_resp_4', 'tel1_resp_5', 'tel1_resp_6', 'tel1_resp_7'],
    'tel_secondaire_resp_final': ['tel2_resp_1', 'tel2_resp_2', 'tel2_resp_3', 'tel2_resp_4', 'tel2_resp_5', 'tel2_resp_6', 'tel2_resp_7', 'tel_secondaire_autre_1'],

    # 2. INFORMATIONS SUR L'ORGANISATION / ENTREPRISE
    'nom_structure_final': ['nom_structure_1', 'nom_structure_2', 'nom_structure_3', 'nom_structure_4', 'nom_structure_5'],
    'type_structure_final': ['type_structure_1', 'type_structure_2', 'statut_juridique_3', 'statut_juridique_4', 'statut_juridique_5'],
    'autres_structure_final': ['autres_structure_1', 'autres_structure_2', 'autres_structure_3', 'autres_structure_4', 'autres_structure_5'],
    'effectif_final': ['effectif_1', 'effectif_2', 'effectif_3', 'effectif_4', 'effectif_5'],
    'nb_femmes_final': ['nb_femmes_1', 'nb_femmes_2', 'nb_femmes_3', 'nb_femmes_4', 'nb_femmes_5'],
    'nb_hommes_final': ['nb_hommes_1', 'nb_hommes_2', 'nb_hommes_3', 'nb_hommes_4', 'nb_hommes_5'],
    'date_creation_final': ['date_creation_1', 'date_creation_2', 'date_creation_3', 'date_creation_4', 'date_creation_5'],
    'num_immatriculation_final': ['num_immatriculation_1', 'num_immatriculation_2', 'num_immatriculation_3', 'num_immatriculation_4', 'num_immatriculation_5'],
    'date_immatriculation_final': ['date_immatriculation_1', 'date_immatriculation_2', 'date_immatriculation_3', 'date_immatriculation_4', 'date_immatriculation_5'],
    'adresse_siege_final': ['adresse_siege_1', 'adresse_siege_2', 'adresse_siege_3', 'adresse_siege_4', 'adresse_siege_5'],
    'email_structure_final': ['email_orga_1', 'email_orga_2', 'email_entreprise_3', 'email_entreprise_4', 'email_entreprise_5'],

    # 3. STATUTS (Famille et Foncier)
    'statut_famille_final': ['statut_famille_1', 'statut_famille_2', 'statut_famille_3', 'statut_famille_4', 'statut_famille_5'],
    'statut_foncier_resp_final': ['statut_foncier_resp_1', 'statut_foncier_resp_2', 'statut_foncier_resp_3', 'statut_foncier_resp_4', 'statut_foncier_resp_5'],
    'statut_foncier_unite_final': ['statut_foncier_unite_3', 'statut_foncier_unite_4', 'statut_foncier_unite_5'],

    # 4. COORDONNÉES GPS
    'gps_final': ['gps_1', 'gps_2', 'gps_3', 'gps_4', 'gps_5'],
    'gps_lat_final': ['gps_lat_1', 'gps_lat_2', 'gps_lat_3', 'gps_lat_4', 'gps_lat_5'],
    'gps_lon_final': ['gps_lon_1', 'gps_lon_2', 'gps_lon_3', 'gps_lon_4', 'gps_lon_5'],
    'gps_alt_final': ['gps_alt_1', 'gps_alt_2', 'gps_alt_3', 'gps_alt_4', 'gps_alt_5'],
    'gps_prec_final': ['gps_prec_1', 'gps_prec_2', 'gps_prec_3', 'gps_prec_4', 'gps_prec_5'],

    # 5. SPÉCIFIQUE PRT (Superficie et Production Générale)
    'superficie_prt_final': ['superficie_prt_1', 'superficie_prt_2', 'superficie_prt_6', 'superficie_prt_autre'],
    'vol_prod_prt_final': ['vol_prod_prt_2', 'vol_prod_prt_autre'],
    
    # Détails de production spécifiques au Groupe 1 (inclus pour uniformiser les noms et la suppression)
    'vol_prod_souchet_final': ['vol_prod_souchet_1'],
    'vol_prod_manioc_final': ['vol_prod_manioc_1'],
    'vol_prod_patates_final': ['vol_prod_patates_1'],
    'vol_prod_ignames_final': ['vol_prod_ignames_1'],
    
    'autres_productions_final': ['autres_productions_1', 'autres_productions_2', 'autres_productions_3', 'autres_productions_4', 'autres_productions_5', 'autres_productions_autre_1'],

    # 6. PRODUITS DÉRIVÉS ET COMMERCIALISÉS
    'prod_transformes_final': ['prod_transformes_3', 'prod_transformes_autre'],
    'prod_commercialises_final': ['prod_commercialises_4'],
    'prod_commercialises_manioc_final': ['prod_commercialises_manioc_4'],
    'prod_exportes_final': ['prod_exportes_5', 'prod_exportes_tubercules'],
    'autres_derives_final': ['autres_derives_3', 'autres_derives_4', 'autres_derives_5'],

    # 7. VOLUMES (Transformation, Achat, Vente)
    'vol_transforme_final': ['vol_transforme_3', 'vol_transforme_autre_1'],
    'vol_achete_final': ['vol_achete_4', 'vol_achete_5'],
    'vol_vente_final': ['vol_vendu_3', 'vol_vendu_4', 'vol_vendu_5', 'vol_vente_tubercules_1', 'vol_vente_prt_1', 'vol_vente_prt_2'],

    # 8. CERTIFICATIONS
    'type_certif_final': ['type_certif_3', 'type_certif_5'],
    'nom_certif_final': ['nom_certif_3'],
    
    # 9. FAÎTIÈRES
    'orga_communale_final': ['orga_communale_1', 'orga_communale_2'],
    'orga_prefectorale_final': ['orga_prefectorale_1', 'orga_prefectorale_2'],
    'union_membre_final': ['union_membre_1', 'union_membre_2']
}

def fusionner_col(df,dictionnaire):
    for base_final, liste_colonnes in dictionnaire.items():
        df[base_final] = df[liste_colonnes[0]]
        for liste_actuelle in liste_colonnes[1:]:
            df[base_final] = df[base_final].fillna(df[liste_actuelle])
    return df
df = fusionner_col(df, fusions_a_faire_prt)
df.head()

C:\Users\DELL\AppData\Local\Temp\ipykernel_33120\3738733374.py:74: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[base_final] = df[base_final].fillna(df[liste_actuelle])

,date_enquete,nom_enqueteur,village,canton,region,type_acteur,type_speculation,nom_repondant,sexe_repondant,instruction_repondant,...,prod_exportes_final,autres_derives_final,vol_transforme_final,vol_achete_final,vol_vente_final,type_certif_final,nom_certif_final,orga_communale_final,orga_prefectorale_final,union_membre_final
0,2026-04-02,BADOHOUN amegno kossi,Sama copé,Gleï,Plateaux,Producteurs,Manioc,Dakpo Akpada Ezi,Homme,Primaire,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-04-02,BADOHOUN amegno kossi,SAMA copé,Gleï,Plateaux,Producteurs,Manioc,KOUDADJE ben,Homme,Collège,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-04-02,BADOHOUN amegno kossi,SAMA copé,Gleï,Plateaux,Producteurs,Manioc,DEGNI Ahogbede,Femme,Aucun,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-04-02,BADOHOUN amegno kossi,SAMA copé,Gleï,Plateaux,Producteurs,Manioc,HOEDJAGNON houndekon,Homme,Aucun,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-04-02,BADOHOUN amegno kossi,SAMA copé,Gleï,Plateaux,Producteurs,Manioc,APEDO komi,Homme,Primaire,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
print(df.columns.tolist())

['date_enquete', 'nom_enqueteur', 'village', 'canton', 'region', 'type_acteur', 'type_speculation', 'nom_repondant', 'sexe_repondant', 'instruction_repondant', 'tel_principal_repondant', 'tel_secondaire_repondant', 'email_repondant', 'poste_repondant', 'nom_resp_1', 'sexe_resp_1', 'adresse_resp_1', 'instruction_resp_1', 'tel1_resp_1', 'tel2_resp_1', 'email_resp_1', 'statut_foncier_resp_1', 'nom_structure_1', 'type_structure_1', 'autres_structure_1', 'effectif_1', 'nb_femmes_1', 'nb_hommes_1', 'date_creation_1', 'num_immatriculation_1', 'date_immatriculation_1', 'adresse_siege_1', 'gps_1', 'gps_lat_1', 'gps_lon_1', 'gps_alt_1', 'gps_prec_1', 'email_orga_1', 'statut_famille_1', 'orga_communale_1', 'orga_prefectorale_1', 'union_membre_1', 'superficie_prt_1', 'vol_prod_souchet_1', 'vol_prod_manioc_1', 'vol_prod_patates_1', 'vol_prod_ignames_1', 'autres_productions_1', 'nom_resp_2', 'sexe_resp_2', 'adresse_resp_2', 'instruction_resp_2', 'tel1_resp_2', 'tel2_resp_2', 'email_resp_2', 'statut_foncier_resp_2', 'nom_structure_2', 'type_structure_2', 'autres_structure_2', 'effectif_2', 'nb_femmes_2', 'nb_hommes_2', 'date_creation_2', 'num_immatriculation_2', 'date_immatriculation_2', 'adresse_siege_2', 'gps_2', 'gps_lat_2', 'gps_lon_2', 'gps_alt_2', 'gps_prec_2', 'email_orga_2', 'statut_famille_2', 'orga_communale_2', 'orga_prefectorale_2', 'union_membre_2', 'superficie_prt_2', 'vol_prod_prt_2', 'autres_productions_2', 'nom_resp_3', 'sexe_resp_3', 'adresse_resp_3', 'instruction_resp_3', 'tel1_resp_3', 'tel2_resp_3', 'email_resp_3', 'statut_foncier_resp_3', 'nom_structure_3', 'statut_juridique_3', 'autres_structure_3', 'effectif_3', 'nb_femmes_3', 'nb_hommes_3', 'date_creation_3', 'num_immatriculation_3', 'date_immatriculation_3', 'adresse_siege_3', 'gps_3', 'gps_lat_3', 'gps_lon_3', 'gps_alt_3', 'gps_prec_3', 'email_entreprise_3', 'statut_famille_3', 'statut_foncier_unite_3', 'prod_transformes_3', 'autres_derives_3', 'vol_transforme_3', 'vol_vendu_3', 'type_certif_3', 'nom_certif_3', 'autres_productions_3', 'nom_resp_4', 'sexe_resp_4', 'adresse_resp_4', 'instruction_resp_4', 'tel1_resp_4', 'tel2_resp_4', 'email_resp_4', 'statut_foncier_resp_4', 'nom_structure_4', 'statut_juridique_4', 'autres_structure_4', 'effectif_4', 'nb_femmes_4', 'nb_hommes_4', 'date_creation_4', 'num_immatriculation_4', 'date_immatriculation_4', 'adresse_siege_4', 'gps_4', 'gps_lat_4', 'gps_lon_4', 'gps_alt_4', 'gps_prec_4', 'email_entreprise_4', 'statut_famille_4', 'statut_foncier_unite_4', 'prod_commercialises_4', 'prod_commercialises_manioc_4', 'autres_derives_4', 'vol_achete_4', 'vol_vendu_4', 'autres_productions_4', 'nom_resp_5', 'sexe_resp_5', 'adresse_resp_5', 'instruction_resp_5', 'tel1_resp_5', 'tel2_resp_5', 'email_resp_5', 'statut_foncier_resp_5', 'nom_structure_5', 'statut_juridique_5', 'autres_structure_5', 'effectif_5', 'nb_femmes_5', 'nb_hommes_5', 'date_creation_5', 'num_immatriculation_5', 'date_immatriculation_5', 'adresse_siege_5', 'gps_5', 'gps_lat_5', 'gps_lon_5', 'gps_alt_5', 'gps_prec_5', 'email_entreprise_5', 'statut_famille_5', 'statut_foncier_unite_5', 'prod_exportes_5', 'autres_derives_5', 'vol_achete_5', 'vol_vendu_5', 'type_certif_5', 'autres_productions_5', 'tel_secondaire_autre_1', 'tel1_resp_6', 'tel2_resp_6', 'superficie_prt_6', 'tel1_resp_7', 'tel2_resp_7', 'vol_transforme_autre_1', 'superficie_prt_autre', 'vol_prod_prt_autre', 'autres_productions_autre_1', 'prod_transformes_autre', 'vol_vente_tubercules_1', 'vol_vente_prt_1', 'vol_vente_prt_2', 'prod_exportes_tubercules', 'nom_resp_final', 'sexe_resp_final', 'adresse_resp_final', 'instruction_resp_final', 'email_resp_final', 'tel_principal_resp_final', 'tel_secondaire_resp_final', 'nom_structure_final', 'type_structure_final', 'autres_structure_final', 'effectif_final', 'nb_femmes_final', 'nb_hommes_final', 'date_creation_final', 'num_immatriculation_final', 'date_immatriculation_final', 'adresse_siege_final', 'email_structure_final', 'statut_famille_final', 'statut_foncier_resp_final', 'statut_foncier_unite_final', 'gps_final', 'gps_lat_final', 'gps_lon_final', 'gps_alt_final', 'gps_prec_final', 'superficie_prt_final', 'vol_prod_prt_final', 'vol_prod_souchet_final', 'vol_prod_manioc_final', 'vol_prod_patates_final', 'vol_prod_ignames_final', 'autres_productions_final', 'prod_transformes_final', 'prod_commercialises_final', 'prod_commercialises_manioc_final', 'prod_exportes_final', 'autres_derives_final', 'vol_transforme_final', 'vol_achete_final', 'vol_vente_final', 'type_certif_final', 'nom_certif_final', 'orga_communale_final', 'orga_prefectorale_final', 'union_membre_final']

In [42]:
liste_a_supprimer = []

for liste_ancienne in fusions_a_faire_prt.values():
    liste_a_supprimer.extend(liste_ancienne)


liste_a_supprimer = list(set(liste_a_supprimer))

df= df.drop(columns = liste_a_supprimer)

print(df.columns.tolist())

['date_enquete', 'nom_enqueteur', 'village', 'canton', 'region', 'type_acteur', 'type_speculation', 'nom_repondant', 'sexe_repondant', 'instruction_repondant', 'tel_principal_repondant', 'tel_secondaire_repondant', 'email_repondant', 'poste_repondant', 'nom_resp_final', 'sexe_resp_final', 'adresse_resp_final', 'instruction_resp_final', 'email_resp_final', 'tel_principal_resp_final', 'tel_secondaire_resp_final', 'nom_structure_final', 'type_structure_final', 'autres_structure_final', 'effectif_final', 'nb_femmes_final', 'nb_hommes_final', 'date_creation_final', 'num_immatriculation_final', 'date_immatriculation_final', 'adresse_siege_final', 'email_structure_final', 'statut_famille_final', 'statut_foncier_resp_final', 'statut_foncier_unite_final', 'gps_final', 'gps_lat_final', 'gps_lon_final', 'gps_alt_final', 'gps_prec_final', 'superficie_prt_final', 'vol_prod_prt_final', 'vol_prod_souchet_final', 'vol_prod_manioc_final', 'vol_prod_patates_final', 'vol_prod_ignames_final', 'autres_productions_final', 'prod_transformes_final', 'prod_commercialises_final', 'prod_commercialises_manioc_final', 'prod_exportes_final', 'autres_derives_final', 'vol_transforme_final', 'vol_achete_final', 'vol_vente_final', 'type_certif_final', 'nom_certif_final', 'orga_communale_final', 'orga_prefectorale_final', 'union_membre_final']

In [43]:
print(df['region'].value_counts())

region
Centrale             417
Plateaux             301
MARITIME             277
Centrale             202
Kara                 128
KARA                 116
MARITIME             113
Maritime              77
Plateau               76
Kara                  70
Plateau               65
Plateaux              52
MARITIMES             31
MARITIMES             29
Maritime              24
kARA                   2
KARA                   2
Mariti6                1
plateaux               1
Centrale               1
 Centrale              1
M'poti                 1
KOMLANDJIN KOFFI       1
Maïs                   1
Kpime                  1
Tomegbe                1
X                      1
Name: count, dtype: int64

In [44]:
# ÉTAPE 1 : Le grand coup de balai automatique
# On enlève les espaces/sauts de ligne parasites et on met tout en majuscules
df['region'] = df['region'].str.strip().str.upper()

# ÉTAPE 2 : Le dictionnaire des corrections chirurgicales
# Tout est écrit en majuscules car l'étape 1 a déjà fait son travail

corrections_regions_prt = {
    # Région des Plateaux
    'PLATEAU': 'PLATEAUX',
    'KPIME': 'PLATEAUX',       # L'enquêteur a mis le canton/village (Kpalimé)
    'TOMEGBE': 'PLATEAUX',     # L'enquêteur a mis le canton/village (Badou)
    
    # Région Maritime
    'MARITIMES': 'MARITIME',
    'MARITI6': 'MARITIME',     # Faute de frappe
    
    # Valeurs totalement aberrantes 
    "M'POTI": 'CENTRALE',             # Village non identifié
    'KOMLANDJIN KOFFI': 'MARITIME',   # Nom de personne
    'MAÏS': 'MARITIME',               # Spéculation
    'X': 'A_VERIFIER'                   # Inconnu
}

# On applique le dictionnaire
df['region'] = df['region'].replace(corrections_regions_prt)

# ÉTAPE 3 : La vérification finale
print("Voici les régions après le nettoyage :")
print(df['region'].value_counts())

Voici les régions après le nettoyage :
region
CENTRALE      622
MARITIME      554
PLATEAUX      497
KARA          318
A_VERIFIER      1
Name: count, dtype: int64

In [45]:
# On remplace le texte "_final" par "rien du tout" (une chaîne de caractères vide '')
df.columns = df.columns.str.replace('_final', '')

# On affiche le résultat pour admirer le travail !
print(df.columns.tolist())

['date_enquete', 'nom_enqueteur', 'village', 'canton', 'region', 'type_acteur', 'type_speculation', 'nom_repondant', 'sexe_repondant', 'instruction_repondant', 'tel_principal_repondant', 'tel_secondaire_repondant', 'email_repondant', 'poste_repondant', 'nom_resp', 'sexe_resp', 'adresse_resp', 'instruction_resp', 'email_resp', 'tel_principal_resp', 'tel_secondaire_resp', 'nom_structure', 'type_structure', 'autres_structure', 'effectif', 'nb_femmes', 'nb_hommes', 'date_creation', 'num_immatriculation', 'date_immatriculation', 'adresse_siege', 'email_structure', 'statut_famille', 'statut_foncier_resp', 'statut_foncier_unite', 'gps', 'gps_lat', 'gps_lon', 'gps_alt', 'gps_prec', 'superficie_prt', 'vol_prod_prt', 'vol_prod_souchet', 'vol_prod_manioc', 'vol_prod_patates', 'vol_prod_ignames', 'autres_productions', 'prod_transformes', 'prod_commercialises', 'prod_commercialises_manioc', 'prod_exportes', 'autres_derives', 'vol_transforme', 'vol_achete', 'vol_vente', 'type_certif', 'nom_certif', 'orga_communale', 'orga_prefectorale', 'union_membre']

In [46]:
for col in df.columns:
    print(f'____{col}____')
    print(df[col].value_counts())
    print('\n')

____date_enquete____
date_enquete
2026-04-30    180
2026-04-27    158
2026-04-25    142
2026-04-28    134
2026-04-24    108
2026-05-04    101
2026-04-29     95
2026-05-05     82
2026-04-23     73
2026-04-17     68
2026-04-26     67
2026-04-14     65
2026-05-02     61
2026-04-16     60
2026-05-15     53
2026-04-13     48
2026-05-14     43
2026-05-06     40
2026-04-20     40
2026-04-18     39
2026-05-03     36
2026-04-15     36
2026-04-22     30
2026-05-01     28
2026-04-03     26
2026-05-09     22
2026-04-21     21
2026-05-07     17
2026-04-08     13
2026-05-10     13
2026-04-02     11
2026-05-11     10
2026-04-12     10
2026-04-06      9
2026-04-19      9
2026-04-09      8
2026-04-11      8
2026-05-08      8
2026-05-16      8
2026-04-07      5
2026-04-10      2
2026-05-12      2
2026-02-10      1
2011-05-16      1
2026-02-11      1
Name: count, dtype: int64


____nom_enqueteur____
nom_enqueteur
BALAWIA ATAWA MEDINABA         173
KADJETA TCHILAABALO            167
TONOU Koami johanes            151
SEDALO KANGNI                  141
SEIBOU ALHASSANE               127
Wadja abina                    127
BADOHOUN Amegno kossi          111
ISSIFOU Aboulaye               108
Eviwounou komla                 95
Kawessina kossi                 80
DJERI MOUDASSIROU               73
SEDALO KANGNI                   65
Eviwounou Komla                 64
AHONTO Attitso Kokou Dodji      61
DJERI MOUDASSIROU               47
Kawessina kossi                 45
ABAGLO AYITE ROBERT             39
BADOHOUN amegno kossi           38
BADOHOUN Amegno kossi           38
ISSIFOU Aboulaye                33
BALAWIA ATAWA MEDINABA          30
AHONTO Attitso Kokou Dodji      20
MAMAH Yakoubou                  18
ABAGLO AYITE ROBERT             17
DJERI  MOUDASSIROU              14
BADOHOUN amegno kossi           13
Wadja abina                     12
Kawessina kossi.                11
SEIBOU Alhassane                10
Eviwounou komla                  7
KEZIRE LAKASSI-KAZA              5
DJERI  MOUDASSIROU               5
Kawessina kossi..                4
Eviwounou Komla                  4
AHONTO Attitso Kokou             4
KEZIRE LAKASSI-KAZA              3
SEIBOU  Alhassane                3
KADJETA TCHILAABALO              2
DJERI MOUDAISSIROU               2
Wadja Abina                      2
POINADA YAKPADAN MANDE           2
POINADA YAKPADAN MANDE           2
TONOU Koami johanes              2
BALAWIA Atawa Medinaba           1
DJERI  MOUDASSIROU\n             1
Vumadi                           1
SEIBOU ALHASSANE                 1
DJERI                            1
DJERI. MOUDASSIROU               1
Eviwounou                        1
Kawessina kossi...               1
Wadja                            1
Tonou Koami johanes              1
AHONTO ATTITSO KOKOU DODJI       1
AHONTO Attitso kokou Dodji       1
WADJA abina                      1
MAMAH Yakoubou                   1
Kawessina kossi                  1
Kawessina.. kossi                1
LAW                              1
Name: count, dtype: int64


____village____
village
BADOUGBE           73
Lama               72
AKEPE              60
Kpovegan           55
Atafa2             51
                   ..
Château             1
Tsive               1
Hanyigba Douga      1
E                   1
Yokele              1
Name: count, Length: 408, dtype: int64


____canton____
canton
Kamboli         134
KEVE            106
Amoussoukope     78
Djemegni         72
Boulohou         72
               ...
Kadafe            1
H                 1
Agome kpodzi      1
Voleve            1
Z                 1
Name: count, Length: 224, dtype: int64


____region____
region
CENTRALE      622
MARITIME      554
PLATEAUX      497
KARA          318
A_VERIFIER      1
Name: count, dtype: int64


____type_acteur____
type_acteur
Producteurs         1748
Transformateurs      197
Commerçants           36
Semenciers             9
Exportateurs           2
Name: count, dtype: int64


____type_speculation____
type_speculation
Manioc                                1504
Manioc Igname                          282
Igname                                  74
Manioc Igname Patate douce              45
Manioc Patate douce                     45
Igname Manioc                           17
Patate douce                             8
Patate douce Manioc                      4
Manioc Igname Patate douce Souchet       3
Manioc Patate douce Igname               3
Igname Patate douce                      2
Manioc Souchet                           2
Patate douce Igname                      1
Souchet                                  1
Manioc Patate douce Igname Souchet       1
Name: count, dtype: int64


____nom_repondant____
nom_repondant
Avosse Abra Akofa    4
Anyi komi awumé      4
Eviwounou Komla      4
Alassane kokou       3
Kpovitô missihoun    3
                    ..
Amigo Etonam         1
Adake Joseph         1
Abalo Komi           1
Wagna Kerim          1
TETI koffi           1
Name: count, Length: 1910, dtype: int64


____sexe_repondant____
sexe_repondant
Homme    1303
Femme     689
Name: count, dtype: int64


____instruction_repondant____
instruction_repondant
Primaire            609
Collège             580
Aucun               535
Lycée               190
Université           66
Ecole coranique      12
Name: count, dtype: int64


____tel_principal_repondant____
tel_principal_repondant
70398558.0    11
90189662.0     8
98460558.0     8
91912012.0     5
92445964.0     5
              ..
99455629.0     1
91639591.0     1
79565059.0     1
93533005.0     1
91889171.0     1
Name: count, Length: 1747, dtype: int64


____tel_secondaire_repondant____
tel_secondaire_repondant
91451595.0    7
99843240.0    4
93170476.0    3
97753294.0    3
98045532.0    3
             ..
91995829.0    1
92005729.0    1
98949002.0    1
72587874.0    1
98555805.0    1
Name: count, Length: 203, dtype: int64


____email_repondant____
email_repondant
Nean                                137
-                                    25
Nean                                 24
eviwounoukomla@gmail.com              4
+                                     3
.                                     2
RAS                                   1
Koffilambli@gmail.com                 1
Activisiontogo@gmail.com              1
atamedi03@gmail.com                   1
almoustafatagba@gmail.com             1
abdousamadoutchalalaou@gmail.com      1
akorikomouhamedrabiou@gmail.com       1
bintoukezire@.com                     1
asmaissaka@gmail.com                  1
Gnansatchassinam@                     1
kataglo@gmail.com                     1
Mensahessaboy57@gmail.com             1
fermealbarka@gmail.com                1
gaecrenaissance@gmail.com             1
preabaloatani@gmail.com               1
djmoudas28@gmail.com                  1
beyelijustin@gmail.com                1
nagbassaou@gmail.com                  1
On                                    1
sitasaharou60@gmail.com               1
songhaiabdouyakini87@gmail.com        1
Seidoukokou@gmail.com                 1
samoudinetchassala64@gmail.com        1
touyaba@gmail.com                     1
Matoswépassayi@gmail.com              1
Françoislegénie0@gmail.Com            1
issifoua@gmail.com                    1
lucieayateto@gmail.com                1
abossitoyi@gmail.com                  1
mabewaantona@gmail.com                1
abdouraoufou@gmail.com                1
ourotoumohamed44@gmail.com            1
abdoudjamiouo@gmail.com               1
skpron21@gmail.com                    1
ayibagna@gmail.com                    1
kadjetastan@gmail.com                 1
idrissouwadja20@gmail.com             1
ouroakononf@gmail.com                 1
essolizamagi@gmail.com                1
mouviyaoflorant@.com                  1
Name: count, dtype: int64


____poste_repondant____
poste_repondant
Membre                    169
Président                 163
Président                 151
Producteur individuel     120
Kara                      111
                         ...
Cordonateur                 1
Président CS                1
2e rapporteur CS            1
Trésorière CG               1
1er rapporteur CS           1
Name: count, Length: 145, dtype: int64


____nom_resp____
nom_resp
Gnansa tchassinam      135
TOGBE Hoenivo           34
ALASSANI KASSIMOU       23
HOUENOU Nodjignon       22
KOUDASSE Afantchawo     21
                      ...
Dougo Koudzo             1
Adake Joseph             1
Abalo Komi               1
Dekpe Kodzovi            1
Eviwounou kossi          1
Name: count, Length: 1498, dtype: int64


____sexe_resp____
sexe_resp
Homme    1321
Femme     671
Name: count, dtype: int64


____adresse_resp____
adresse_resp
Tchamba, kamboli, Atafa2       51
Haho2, Djemegni, kpovegan      47
VO TOGOVILLE BADOUGBE          42
YOMETSIN                       42
VO AKOUMAPE                    31
                               ..
Kloto1 Tome Agripper Todzi      1
Kloto1 kpadape Gagou            1
Kloto1 kpadape Gagou            1
Kloto1 Gbalave                  1
Kloto1 Tove Ati                 1
Name: count, Length: 623, dtype: int64


____instruction_resp____
instruction_resp
Aucun               565
Primaire            563
Collège             496
Lycée               273
Université           87
Ecole coranique       7
Name: count, dtype: int64


____email_resp____
email_resp
Nean                              133
-                                  32
Nean                               28
djmoudas28@gmail.com                5
eviwounoukomla@gmail.com            4
Gnansatchassinam@                   3
+                                   3
_                                   1
atamedi03@gmail.com                 1
activisiontogo@gmail.com            1
fermealbarka@gmail.com              1
preabaloatani@gmail.com             1
touyaba@gmail.com                   1
beyelijustin@gmail.com              1
sitasaharou60@gmail.Com             1
bintoukezire@.com                   1
songhaiabdouyakini87@gmail.com      1
Seidoukokou@gmail.com               1
Matoswépassayi@gmail.com            1
samoudinetchassala64@gmail.com      1
bawinayabass@gmail.cm               1
Gnansa tchassinam @                 1
Françoislegeni0@gmail.Com           1
issifoua@gmail.com                  1
lucieayateto@gmail.com              1
mangbdav@gmail.com                  1
abdouraoufou@gmail.com              1
abdouraoufou@gmail.com              1
ourotoumohamed44@gmail.com          1
skpron21@gmail.com                  1
kadjetastan@gmail.com               1
essolizamagi@gmail.com              1
Name: count, dtype: int64


____tel_principal_resp____
tel_principal_resp
93921667.0    113
79478242.0     35
92931667.0     27
91761664.0     25
98309091.0     23
             ...
99601670.0      1
99455629.0      1
92819978.0      1
97056670.0      1
91276775.0      1
Name: count, Length: 1366, dtype: int64


____tel_secondaire_resp____
tel_secondaire_resp
99115402.0    20
71971121.0    18
99044524.0    16
79282289.0    13
93622461.0    10
              ..
70797515.0     1
92005729.0     1
98949002.0     1
72587874.0     1
97047333.0     1
Name: count, Length: 147, dtype: int64


____nom_structure____
nom_structure
Champ individuel                                                 127
Individuel                                                        94
UCPRT KEVE                                                        80
UCPRT TOGOVILLE                                                   56
UCPRT AKEPE                                                       53
                                                                ...
Enyo                                                               1
Ogboni                                                             1
Nom entreprise                                                     1
CJDK ( Coopérative des Jeunes pour le Développement de Kpele)      1
DINORCE                                                            1
Name: count, Length: 930, dtype: int64


____type_structure____
type_structure
Individuel                                             998
Société coopérative simplifiée (SCOOPS)                606
Groupement                                             136
Coopérative avec conseil d'administration (COOP CA)    106
Etablissement  ETS                                      77
Groupe de solidarité                                    40
Association                                             11
Union de coopérative                                     7
Autres (préciser)                                        7
SARL                                                     3
SARL U                                                   1
Name: count, dtype: int64


____autres_structure____
autres_structure
-            1
Maïs         1
Anacarde     1
Name: count, dtype: int64


____effectif____
effectif
1.0       772
5.0       131
10.0       74
15.0       73
3.0        71
2.0        64
7.0        63
8.0        59
11.0       59
12.0       55
4.0        54
17.0       48
6.0        46
9.0        42
35.0       37
14.0       32
18.0       31
23.0       31
20.0       29
22.0       29
16.0       29
30.0       28
25.0       26
13.0       22
34.0       10
26.0        9
19.0        9
27.0        8
21.0        6
24.0        6
32.0        4
36.0        3
0.0         3
50.0        2
43.0        2
95.0        2
86.0        1
46.0        1
115.0       1
79.0        1
38.0        1
55.0        1
31.0        1
388.0       1
1713.0      1
56.0        1
29.0        1
123.0       1
145.0       1
45.0        1
53.0        1
63.0        1
33.0        1
40.0        1
60.0        1
65.0        1
160.0       1
28.0        1
120.0       1
Name: count, dtype: int64


____nb_femmes____
nb_femmes
0.0       544
1.0       518
2.0       163
5.0        99
3.0        91
4.0        85
10.0       69
7.0        60
8.0        58
16.0       43
6.0        41
12.0       39
9.0        33
20.0       26
15.0       23
11.0       17
18.0       13
30.0       10
13.0        9
14.0        4
17.0        4
22.0        4
25.0        3
31.0        3
24.0        3
21.0        2
34.0        2
50.0        2
33.0        2
29.0        2
40.0        2
28.0        2
85.0        1
19.0        1
250.0       1
1500.0      1
36.0        1
51.0        1
46.0        1
75.0        1
23.0        1
41.0        1
93.0        1
26.0        1
90.0        1
Name: count, dtype: int64


____nb_hommes____
nb_hommes
1.0      537
0.0      410
2.0      163
3.0      129
5.0      114
4.0       94
7.0       84
6.0       82
8.0       77
13.0      40
19.0      38
10.0      34
11.0      32
17.0      30
9.0       27
27.0      13
15.0      13
12.0      13
29.0       7
16.0       7
22.0       7
14.0       5
21.0       5
18.0       4
33.0       3
28.0       2
30.0       2
20.0       2
23.0       2
62.0       1
36.0       1
47.0       1
49.0       1
213.0      1
138.0      1
70.0       1
72.0       1
65.0       1
24.0       1
25.0       1
35.0       1
50.0       1
67.0       1
Name: count, dtype: int64


____date_creation____
date_creation
2026-04-06    101
2026-05-01     76
2011-05-16     60
2026-04-27     39
2026-04-25     37
             ...
2023-05-15      1
2024-10-11      1
2026-02-27      1
2025-09-15      1
2010-05-17      1
Name: count, Length: 920, dtype: int64


____num_immatriculation____
num_immatriculation
Nean                                118
Nean                                 32
SCS03109/2020MAPAH/SG/DFDTOPA        21
SCS 09951/2025/MAPRASA/SG/DEFA       16
-                                    14
                                   ...
.SCS 6530/2022/MAEDR/SG/DFDTOPA       1
SCS 7388/2023/MAEDR/SG/DFDTOPA        1
SCS 02094/2020/MAPAH/SG/DFDTOPA       1
En cours                              1
CCA 9947/2025/MAu PRASA/SG/DEFA       1
Name: count, Length: 155, dtype: int64


____date_immatriculation____
date_immatriculation
2020-04-27    20
2025-02-21    20
2020-12-21    15
2018-09-06    13
2018-10-29    12
              ..
2023-11-08     1
2026-05-15     1
2026-05-06     1
2026-05-16     1
2025-12-10     1
Name: count, Length: 99, dtype: int64


____adresse_siege____
adresse_siege
BADOUGBE                       57
Atafa2/Tchamba                 52
YOMETSIN                       44
Atiyi                          39
M'poti                         38
                               ..
Kpele Gbaladze                  1
Kpele, kpele -centre Godzo      1
Kpele Gbaladze Tsavie           1
Kpele Gbaladze Anoumou          1
Saïboudè(+228)72571742          1
Name: count, Length: 726, dtype: int64


____email_structure____
email_structure
Nean                                           124
Nean                                            40
-                                               24
.                                                5
Scoopsterrebeni@gmail.com                        1
mephraim507@gmail.com                            1
RAS                                              1
91431100                                         1
90352823.0                                       1
laminousabi@gmail.com                            1
scoopsadeguelidekedjikandjo@gmail.com            1
91189806                                         1
93089097.0                                       1
92381628.0                                       1
70745783.0                                       1
91820478.0                                       1
+                                                1
Gnansatchassinam@                                1
aloguedocoop20@gmail.com                         1
scoopsbigadouguesoulombou@gmail.com              1
92013310.0                                       1
UCPRT TOGOVILLE                                  1
fermealbarka@gmail.com                           1
Agbassikiti/Tchamba                              1
beyelijustin@gmail.com                           1
dfdtopa@agriculture.tg/dfdtopamaep@yahoo.fr      1
eviwounoukomla@gmail.com                         1
Yobomé                                           1
Yobo sedzro                                      1
dfdtopamaep@yahoo.fr                             1
ajatg@yahoo.fr                                   1
lucieayateto@gmail.com                           1
togoscjldt777@gmail.com                          1
abdouraoufou@gmail.com                           1
ourotoumohamed44@gmail.com                       1
skpron21@gmail.com                               1
Fio Kondji Glidji Lacs                           1
Name: count, dtype: int64


____statut_famille____
statut_famille
Membre actif        1340
Membre potentiel     608
Membre inactif        44
Name: count, dtype: int64


____statut_foncier_resp____
statut_foncier_resp
Propriétaire        1138
Locataire / bail     851
Locataire              3
Name: count, dtype: int64


____statut_foncier_unite____
statut_foncier_unite
Propriétaire        128
Locataire / bail    105
Locataire             1
Name: count, dtype: int64


____gps____
gps
6.8770516 0.6498875 0.0 500.0                  13
6.4145015 1.3323113 0.0 699.999                 9
6.9079529 0.606355 0.0 100.0                    6
9.5856139 1.1837214 347.70001220703125 77.6     6
6.3363649 1.3311063 0.0 1100.0                  5
                                               ..
6.8690654 0.6054671 0.0 699.999                 1
6.8315381 0.5944842 1059.582 3.043              1
7.2478441 1.2458997 212.04931640625 38.945      1
6.8771487 0.6498875 0.0 500.0                   1
6.857509 1.3752835 153.68634033203125 4.933     1
Name: count, Length: 1917, dtype: int64


____gps_lat____
gps_lat
6.877052    13
6.414502    10
9.585614     6
6.907953     6
9.585615     5
            ..
7.129148     1
6.869065     1
6.831538     1
6.239407     1
9.418095     1
Name: count, Length: 1833, dtype: int64


____gps_lon____
gps_lon
0.649887    14
1.332311    10
0.606355     7
1.163647     6
1.183721     6
            ..
0.731067     1
0.731402     1
0.731111     1
0.605467     1
1.245896     1
Name: count, Length: 1845, dtype: int64


____gps_alt____

In [47]:
import pandas as pd

# 1. Nettoyage de base habituel
df['nom_enqueteur'] = df['nom_enqueteur'].astype(str).str.replace('"', '', regex=False)
df['nom_enqueteur'] = df['nom_enqueteur'].str.strip().str.upper()

# 2. Dictionnaire de corrections Regex adapté à cette 3ème liste
corrections_enqueteurs_3 = {
    r'^.*BADOHOUN.*$': 'BADOHOUN AMEGNO KOSSI',
    r'^.*DJERI.*$': 'DJERI MOUDASSIROU',
    r'^.*KEZIRE.*$': 'KEZIRE LAKASSI-KAZA',
    r'^.*EVIWOUNOU.*$': 'EVIWOUNOU KOMLA',
    r'^.*WADJA.*$': 'WADJA ABINA',
    r'^.*BALAWIA.*$': 'BALAWIA ATAWA MEDINABA',
    r'^.*ISSIFOU.*$': 'ISSIFOU ABOULAYE',
    r'^.*TONOU.*$': 'TONOU KOAMI JOHANES',
    r'^.*SEDALO.*$': 'SEDALO KANGNI',
    r'^.*KADJETA.*$': 'KADJETA TCHILAABALO',
    r'^.*KAWESSINA.*$': 'KAWESSINA KOSSI',
    r'^.*ABAGLO.*$': 'ABAGLO AYITE ROBERT',
    r'^.*SEIBOU.*$': 'SEIBOU ALHASSANE',
    r'^.*AHONTO.*$': 'AHONTO ATTITSO KOKOU DODJI',
    r'^.*POINADA.*$': 'POINADA YAKPADAN MANDE',
    r'^.*MAMAH.*$': 'MAMAH YAKOUBOU',
    r'^.*VUMADI.*$': 'VUMADI'
}

# 3. Application du remplacement
df['nom_enqueteur'] = df['nom_enqueteur'].replace(corrections_enqueteurs_3, regex=True)

# Note pour le "LAW" à la fin de votre liste : 
# S'il s'agit d'une erreur de frappe de l'enquêteur "Kawessina", vous pouvez l'ajouter manuellement :
# df['nom_enqueteur'] = df['nom_enqueteur'].replace('^LAW$', 'KAWESSINA KOSSI', regex=True)

# 4. Vérification finale
print(df['nom_enqueteur'].value_counts())

nom_enqueteur
SEDALO KANGNI                 206
BALAWIA ATAWA MEDINABA        204
BADOHOUN AMEGNO KOSSI         200
EVIWOUNOU KOMLA               171
KADJETA TCHILAABALO           169
TONOU KOAMI JOHANES           154
DJERI MOUDASSIROU             144
KAWESSINA KOSSI               143
WADJA ABINA                   143
SEIBOU ALHASSANE              141
ISSIFOU ABOULAYE              141
AHONTO ATTITSO KOKOU DODJI     87
ABAGLO AYITE ROBERT            56
MAMAH YAKOUBOU                 19
KEZIRE LAKASSI-KAZA             8
POINADA YAKPADAN MANDE          4
VUMADI                          1
NAN                             1
LAW                             1
Name: count, dtype: int64

In [48]:
df['date_enquete'] = pd.to_datetime(df['date_enquete'],errors = 'coerce')
df['date_enquete'] = df['date_enquete'].dt.date

print(df['date_enquete'].head())

0    2026-04-02
1    2026-04-02
2    2026-04-02
3    2026-04-02
4    2026-04-02
Name: date_enquete, dtype: object

In [50]:
# première lettre en majuscule et le reste en minuscule
colonne_a_convertir = ['village', 'canton','adresse_resp','nom_repondant']

# Boucle pour changer la première lettre
for col in colonne_a_convertir:
    df[col] = df[col].astype(str).str.capitalize()

df[colonne_a_convertir]=df[colonne_a_convertir].replace('Nan','')

In [51]:
# Sauvegarde en Excel
df.to_excel("PRT_propre4.xlsx", index=False)